### ISSUE TITLE
Library advice on OA options

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#173]
@jldimond - have you got any response from Library on best approach for OA preprint/postprint option?

**Comment by jldimond** [comment]
Yes I did get a response. Basically he said that it sounds like a post-print is OK, and that posting the uncorrected proof would probably be OK. He said that if they have any issues with what you post you can always change it.

**Comment by jldimond** [comment]
Here is a transcript of our discussion:

Question History:

Patron: Qwidget: Hi,

Librarian 1: Librarian 'Alyssa (U-Washington)' has joined the session.

Librarian 1: Hi there!

Patron: I have an article in press at a Wiley journal (Molecular Ecology)

Patron: I'm wondering about the best way to publish a pre- or post-print.

Patron: It seems like some folks put up the uncorrected proof on their websites - is this kosher?

Librarian 1: Hmm, I'm not our resident copyright/open access expert! But, let me take a look at some of the guidelines we have on our site & see if I can help. I'll be right back...

Patron: Thanks! The information I found on Sherpa (?) was sort of vague.

Librarian 1: Ok, so then it sounds like you've already seen this page (or maybe its equivalent?): http://www.lib.washington.edu/scholpub/options/determine

Patron: Yes

Patron: It appears that a post-print is allowable, but it is vague.

Librarian 1: Got it - so it sounds like you are mostly just trying to figure out the allowances that Molecular Ecology will make.

Patron: Yes

Patron: Ideally, I would like to archive the uncorrected proof as I have seen others do, but I'm not sure this is OK. The next best alternative, it seems, is to use something like ArXiv to archive a post-print.

Librarian 1: Ok, I think it might be best (& most efficient) if I forward your question along to one of the librarians who works more with open access/scholarly publishing issues.

Librarian 1: He can get back to you with more information via email. Does that sound ok?

Patron: That would be great! Thank you!

Librarian 1: Ok - great. When we disconnect here, I'll forward this to Mel DeSart. You can expect a response back via email.

Librarian 1: Thanks for your patience!

Patron: No problem, thanks for your time!

Librarian 1: Enjoy the rest of your day (& congratulations on getting the article in Molecular Ecology).

Librarian 1: Librarian ended chat session.

Hello Library Patron



You ask about "publishing" a pre or post-print, but don't necessarily indicated where you want to do that.  You mention that others have put up pre-prints on web sites, which is an option, but not a particularly good one, given the lack of permanence of the average web page.  UW has an institutional repository just for the kind of content you're describing.  It's called ResearchWorks, and more info can be found at https://researchworks.lib.washington.edu/rw-archive.html.

As for what you're _allowed_ to post, pre-review preprints are allowed by Wiley under pretty much all conditions, and a post-print (a much better option) is allowed under the following conditions, as outlined in the Sherpa/RoMEO entry for Molecular Ecology:

    Some journals have separate policies, please check with each journal directly
    On author's personal website, institutional repositories, arXiv, AgEcon, PhilPapers, PubMed Central, RePEc or Social Science Research Network
    Author's pre-print may not be updated with Publisher's Version/PDF
    Author's pre-print must acknowledge acceptance for publication
    Non-Commercial
    Publisher's version/PDF cannot be used
    Publisher source must be acknowledged with citation
    Must link to publisher version with set statement (see policy)
    If OnlineOpen is available, BBSRC, EPSRC, MRC, NERC and STFC authors, may self-archive after 12 months
    If OnlineOpen is available, AHRC and ESRC authors, may self-archive after 24 months

Archiving the post-print is always a better bet because that version is post-peer review and the content (text, figures, illustrations, etc.) in the post-print should match what will appear in the published version - the only real differences should be in formatting.  That allows others accessing your work via the post-print to be seeing the same content as what appears in the published version, even if it looks a little different. 

If you have additional questions about this, feel free to contact me directly.

Mel

 

Mel DeSart

desart@uw.edu


Hi Mel,

Thanks for your response to my query about archiving a post-print. I guess my main question is whether the publisher would have any issue with me archiving the uncorrected proof as the (almost) post-print. The uncorrected proof is nice because it has almost the same formatting/readability as the final version. My understanding is that the publisher does not want you to archive the final "version of record", so the uncorrected proof would qualify because it is not the final version. Would you agree?

Thanks,

James


Mels' reply:

Sometimes this is a matter of semantics.  The phrase the library world uses for which version can be deposited is the “author’s final” version, whatever that may be.  With some publishers that’s post peer review but not formatted.  It sounds like with Wiley that there author’s final has much of the formatting already in place.  I’d guess I’d go ahead and put it up, as long as you also adhere to all the restrictions that Wiley says need to go along for the ride.  If they see and don’t like it, they’ll let you know and you can sub in a different version that IS acceptable to them.

 

mel

**Comment by jldimond** [comment]
So I guess my preference would be to post the uncorrected proof, because it retains almost the same format as the published version. I am generally not a big fan of pre- or post-prints that have Word-like formatting and have lots of pages. It makes me not want to print or read them, they just seem really cumbersome. That is my reasoning for favoring the uncorrected proof idea. But if you prefer the arXiv option, then I'm OK with that.

**Comment by sr320** [comment]
Where would you put the uncorrected proof? And do you know Wiley would allow?

I say go with http://biorxiv.org/ . But open to other legit options.

Note the long Word-like is not necessarily for you but for those without institution subscriptions. Long word-like is better than no access

**Comment by jldimond** [comment]
OK I submitted to UW ResearchWorks archive - they will review it and hopefully get back to me.
