### ISSUE TITLE
Update Googlesheet and Fusion Table with New Sequence data

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#195]
as per https://github.com/sr320/LabDocs/blob/master/DMPseq.md

**Comment by sr320** [comment]
But MBD-BS, BS, data is not in
https://docs.google.com/spreadsheets/d/1r4twxfBHpWfQoznbn2dAQhgMvmlZvQqW9I2_uVZX_aU/edit#gid=0

Also I would say 109 - 113 need more info?  

I guess we could reconsider the DMP? documentation... but for example this is where I go to find out what each library is..

**Comment by sr320** [comment]
Also noted that the  two column PE format has been loss in the fusion table.  

(this probably means the DMP itself needs improvement)

**Comment by kubu4** [comment]
> Also I would say 109 - 113 need more info?

Agreed, but more info is too much for sheet. There are 96 samples multiplexed in 4 of the 5 libraries listed there.

> Also noted that the two column PE format has been loss in the fusion table. 

It's still there. We're so far down the Nightingales sheet, I didn't even realize that those two columns were actually used for anything. Why need additional columns? Data sorts so that paired read files are next to each other (vertically) on sheet.

> (this probably means the DMP itself needs improvement)

Agree with DMP needs improvement. Very tedious to update three separate sheets (Next_gen_seq_library_db, nightingales sheet, nightingales fusion table). In fact, I had thought with the creation of the Nightingales sheet that we were done with Next_gen_seq_library_db (until you pointed out it hadn't been updated the other week).

**Comment by sr320** [comment]
If we have time lets go over the DMP tomorrow and modify accordingly.
I think we have edge cases that might be more the "norm" going forward (ie RAD) and might need to rethink.
