### ISSUE TITLE
Determine if there is a simple GitHub repo backup to NAS

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#269]
If we begin to rely more on GitHub, might be good to set up some automatic backups...

Maybe something along the lines of https://github.com/joeyh/github-backup

though imagine there might be simpler options.

**Comment by kubu4** [comment]
Isn't this overly redundant? Aren't all the repos also "backed up" to everyone's local computers, as is the nature of working with Git? Even if GitHub is down, we still have the repos stored locally on multiple computers.

Also, the Synology NAS servers have a Git app. At some point, I'll see if I can just clone the repos to that...

**Comment by sr320** [comment]
What about a project repo- someone else is working on (maybe online) - I get around to it 6 months later but have not synced, AND Github is down. AND that person is gone. 

I realize this is very, very edge- that is why I indicated "simple" and low priority 👍 

that link also does a bit more.. 
>> including branches, tags, other forks, issues, comments, wikis, milestones, pull requests, watchers, and stars.

**Comment by sr320** [comment]
Related ❔ - 
is this
https://github.com/sr320/LabDocs/tree/master/LabDocs.wiki
the wiki - thus can edit these offline?

I have not seen these in the code before and with my gui, have to clone separately.

**Comment by kubu4** [comment]
I feel like you'd still be in the same boat - you'd still have to run the githubbackup program. If you haven't run it in six months, you'd still be stuck with outdated, local repos.

Yep, wikis can be edited offline. I was working on the LabDocs wiki on my computer, so that's why it's now showing up in the LabDocs code page.

**Comment by kubu4** [comment]
However, as you pointed out, the githubbackup program does offer the other benefits of pulling down branches, tags, etc...

**Comment by sr320** [comment]
But _if_ github was down, I could just open up the csv file from owl?

**Comment by sr320** [comment]
to confirm - edits to LabDocs.wiki does edit the online wiki?

**Comment by kubu4** [comment]
Yes, edits to LabDocs.wiki makes edits to the online wiki. No different than any other aspect of GitHub - still have to commit changes and push the commit to GitHub.

**Comment by kubu4** [comment]
> I have not seen these in the code before and with my gui, have to clone separately.

Yeah, it's sorta weird. It does require separate cloning, but seems to show up in the associated repo after it's been cloned...

>must take at least 5 minutes to update....

I pulled your changes immediately and can see them on that page. Do you not see "Does this alter the wiki?"

**Comment by sr320** [comment]
Yes but it does not show up at
https://github.com/sr320/LabDocs/wiki

❓ 

🐇 🔵

**Comment by kubu4** [comment]
Ah! Weird!

**Comment by kubu4** [comment]
Figured it out. I screwed it up because I cloned the wiki into the LabDocs repo! Wanted the convenience of not having multiple repos called LabDocs, but that won't work. :disappointed: 

Create a clone of the wiki outside of an existing repo and it will work:

[https://github.com/sr320/LabDocs/wiki](https://github.com/sr320/LabDocs/wiki)

**Comment by sr320** [comment]
Moved to #178
