### ISSUE TITLE
Install dammit on hummingbird

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#270]
If at possible -
It would be great to get 
http://www.camillescott.org/dammit/
on hummingbird.

**Comment by kubu4** [comment]
Dammit is installed on Hummingbird and Roadrunner (srlab accounts), but using Docker. A more detailed explanation of why using Docker after a very brief explanation of how to start using Docker so that we can start using dammit...

To begin using the Docker image on Hummingbird or Roadrunner, use the following commands in Terminal:

1. ```eval "$(docker-machine env default)"```
2. ```docker run -p 8787:8787 -p 8888:8888 -v /Users/srlab/data:/root/data -it kubu4/bioinformatics:v11 /bin/bash```

That puts you in to the Docker container to start working with the [various programs that are installed](https://github.com/sr320/LabDocs/blob/master/code/dockerfiles/Dockerfile.bio).

Important note - Due to limitations with Docker and OSX interactions, Docker containers can't access volumes "above" the /Users/username location (e.g. can't read/write to external HDD or different partition). This is important because [Hummingbird is limited on storage space](https://github.com/sr320/LabDocs/issues/257). As such, it may be recommended to use Roadrunner, since it's HDD is significantly larger than Hummingbird...

**Comment by kubu4** [comment]
For more detailed info on using Docker (and understanding what all that gibberish is in #2 above), please see the [Docker manual I put together.](https://github.com/sr320/LabDocs/blob/master/code/docker.md)

Also, the Docker container above is set up to use Jupyter notebooks and R/R Studio (usage of both is explained in that manual linked above).

**Comment by sr320** [comment]
Awesome thanks! 💯

**Comment by kubu4** [comment]
On why I'm using Docker for this:

1. The recommended installation method for dammit is to use: ```conda install dammit``` Unfortunately, the dammit package is not available for OSX 64-bit systems (at least, that's what the error message spits out when trying to install it in that fashion).

2. The installation instructions for dammit were kind of long and tedious and, at times, incorrect. Being able to use ```conda install dammit``` ensures that all the dependencies are installed and work correctly with dammit.

**Comment by kubu4** [comment]
Finally, there tend to be various amounts of "nuances" with Docker at times. Post any problems as an issue and I should be able to help resolve them quickly. Here is one quick tip to employ when using a Docker container (these are from the [Supplemental Info section of that manual](https://github.com/sr320/LabDocs/blob/master/code/docker.md#supplemental-info)):

- To finish using a container AND save its current state (i.e. any changes you've made, files you've saved, etc), press: CTRL-p and then CTRL-q
