### ISSUE TITLE
Does Docker file software list need updating?

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#283]
I did not want to break anything but

is not the list at the top, missing several packages that are listed further down?

https://github.com/sr320/LabDocs/blob/master/code/dockerfiles/Dockerfile.bio

**Comment by kubu4** [comment]
Yes and no. Some packages are dependencies for others. Debatable whether I should list them. Probably don't have dammit listed because the Docker image rebuilds from top to bottom if any changes detected between previous image build. Build takes some time and I wanted dammit to be usable before I left, so didn't add it to package list after I verified dammit compilation was complete.

**Comment by kubu4** [comment]
Of course, you're welcome to edit the list (I've been doing it in alphabetical order). It won't have any impact on existing images/containers.
