### ISSUE TITLE
Take action on genomes..

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#310]
We need to move on these genomes... 

We should discuss how to approach BGI

Also do we have any more material (tissue / DNA) from either of animals sent off for sequencing?

**Comment by kubu4** [comment]
Lots of tissue left.

All DNA I isolated was sent to BGI.

**Comment by sr320** [comment]
Can you go ahead and contact Frank to see if we can get a meeting....
and
Genewiz to get a quote to move forward with the data we have, and maybe more..

**Comment by kubu4** [comment]
Frank from BGI will be in Seattle in a few weeks. Will coordinate meeting time when his travel dates are finalized.

**Comment by sr320** [comment]
Great! Lets go ahead and line up some alternatives

**Comment by kubu4** [comment]
Genewize quote:

$9000 to assemble both genomes. Lead time 6-8 weeks.

**Comment by kubu4** [comment]
Email from Katherine Silliman:
>
Hi,
>
I spoke to a friend of mine who has assembled some butterfly genomes from mate-pair libraries. She recommended the platanus suite as it is easy to use and supposed to be good for heterozygous species. The authors actually tested this program on the gigas genome. Based on what is listed on github, it looks like you have:
- Raw data for all libraries (received 20160127)
- scaffold.fa.fill, Initial genome assembly of unknown parameters (rec' 20160314)
- *fq.gz.clean.dup.clean.gz, Filtered data from the 500, 800, and 300 insert size libraries (rec' 20160512)
- Ostrea_lurida.scafSeq, assembly of 300, 500, and 800 insert libraries
>
So if this is something you want to pursue apart from BGI, I think the approach would be:
1) the libraries that haven't been filtered yet would need to go through the platanus_internal_trim program (insert sizes 5000,10000,5000,10000,2000), 
2) use the small insert libraries for config assembly, 
3) perform scaffolding with the contains and large insert size libraries, 
4) gap-closing with the scaffold and smaller insert libraries
>
An alternative would be having a bioinformatics group work on it. I'll let you know the exact quote from the UChicago group next week, but it sounds like it'd be at least $500.
>
I'm happy to help in any way I can to get a good working assembly, including trying out the pipeline on our high memory cluster, since I think both my 1st chapter and our 2brad/epigenetics paper will be considerably improved with a genome. Let me know what you think!

**Comment by sr320** [comment]
@seanb80 Can you start playing around with the Platanus suite for assembly... maybe see if you can get it installed and do test run with provided data, assuming some is provided.

**Comment by seanb80** [comment]
I currently have Platanus installed, and am downloading a developer suggested dataset for testing. Will update once dataset is downloaded/assembly begun.

**Comment by seanb80** [comment]
I have Platanus functioning with one of the developer suggested dataset (Some butterfly genome) and have successfully trimmed it, and begun the assembly. This is likely too time consuming for the computer I am on, but will see if I can progress into the scaffolding step afterwards. If there is another data set that's more relevant to use, I could switch to that also.
