### ISSUE TITLE
Set up Linux desktops in the lab

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#327]
There are a couple of Linux boxes in Brent's office- lets get them up and operational in the lab

**Comment by seanb80** [comment]
Both Optiplex 755 desktops have been reimaged with 64-bit Ubuntu 14.04.5 and ssh installed and operating. Both machines are 3.0 GHz Core 2 Duos with 2gb of RAM and 200gb of HDD space. 

There was a third, older Optiplex that is a P4, with a  1.5ghz processor, 512mb of ram, and a 20gb hard drive. It's unable to be imaged to ubuntu in it's current state due to the lack of ability to boot off of usb/lack of a dvd drive for a live cd. I'm not sure it's worth putting much effort into it, it would likely only be useful as a load balancer or perhaps a router of some sort (or a door stop)

IP addresses are:

128.95.149.212 (srlab1/scallop)
128.95.149.217 (srlab2/scallop)

What would you like to see installed on these for use long term? Both have platanus on them currently, but little else.

**Comment by sr320** [comment]
Thanks!
