### ISSUE TITLE
Finalize Protein Extraction Protocol

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#333]
@Ellior2 is getting a markdown version of the protein extraction protocol up at
https://github.com/sr320/LabDocs/tree/master/protocols

Once a draft is up lets make sure it is clear to all and we have necessary reagents.

**Comment by Ellior2** [comment]
https://github.com/sr320/LabDocs/blob/master/protocols/ProteinprepforMSMS.md

**Comment by sr320** [comment]
Nice!

**Comment by sr320** [comment]
I have started making a list at the top of the protocol re reagents / supplies..
https://github.com/sr320/LabDocs/blob/master/protocols/ProteinprepforMSMS.md
Please add to, and confirm

**Comment by Ellior2** [comment]
Added some more things to the list.

Clarification question as I can't quite remember:

You can do steps 1-8 from the mini-trypsin digestion before knowing how much protein you have per sample? Then once you quantify the proteins using the BCA assay, you can continue with steps 9-16?

**Comment by sr320** [comment]
@emmats can you clarify

**Comment by Ellior2** [comment]
Also can we get clarification for Step 1 in Sonication:

It states:
Add 100ul 6M urea in 50 mM NH4HCO3 (ammonium bicarbonate).

But really we...
Smash frozen biological material with pestle in centrifuge tube.
Then add (volume?) 50 mM NH4HCO3 (ammonium bicarbonate).
Then add 100ul 6M urea.

Is this correct?

**Comment by emmats** [comment]
First question: Yes, you do not need exactly 100 ug of protein until you start adding enzymes. The other reagent amounts are based on your sample volume. The amount of enzyme added depends on the amount of protein in your sample. You can always do your BCA assay early and do the entire thing on 100 ug of sample.

Second question: Not correct. You  make a solution of 50 mM bicarb + 6M urea.  Here is the link to my notebook entry for digestion: https://www.evernote.com/l/APLBpNYN-VlFvbPyRfi7DbOQX3q2u6s2mbQ

**Comment by Ellior2** [comment]
Thank you @emmats . As far as technical replication goes- we decided to just do this on one sample to verify that there is no variability in our techniques right? So on the first day, for example, I could make 3 replicates of sample #1 starting from sonication (1A, 1B, and 1C)? Is it necessary to do this for each of the 3 extraction sessions?

**Comment by emmats** [comment]
You are referring to technical replication of extractions? And you would digest 1A with the first round, 1B with the second, and 1C with the third?
Did you look at the text book I forwarded to you? Is that what they suggest?

**Comment by Ellior2** [comment]
We decided to cut down the number of samples so I might even be able to do it in one session. In which case, subdividing one of our samples into 3 replicates for digestion would allow us to see potential variability in the digestion process. After desalting, we could also create 3 replicate vials from that same sample to test variability in MSMS. If there is variation in either step, we should be able to tell whether it was during the digestion/desalting or the MSMS. It should only create 2 extra samples for digestion and 4 extra for MSMS.

I'm still confused about the 50mM bicarb + 6M urea. How specifically would I make that solution? I use 500ul 6M urea and add it to how much 50mM bicarb?

**Comment by sr320** [comment]
I suggest adding the presumed method to making everything at the beginning of the protocol - then we will review all.

**Comment by emmats** [comment]
For the bicarb, you make 50 mM NH4HCO3. You then add enough urea to equal 6M.

**Comment by kubu4** [comment]
@emmats - Can you clarify this a bit more? So, what is your final NH4HCO3 concentration???!!

**Comment by kubu4** [comment]
Oh, wait. I hit enter too soon. I see...

The solution (homogenization buffer) should be 50mM NH4HCO3, 6M Urea. 

The confusion stemmed from the wording about in your notebook "Added 500 µl 6M urea in 50 mM bicarb". It sounded like the instructions were to add a solution of urea to a solution of 50mM NH4HCO3.

Thanks! I think we are clear, now.

**Comment by emmats** [comment]
You got it @kubu4 :)

**Comment by Ellior2** [comment]
I updated the protocol with how I think the reagents should be made... please review...
https://github.com/sr320/LabDocs/blob/master/protocols/ProteinprepforMSMS.md

**Comment by Ellior2** [comment]
How to make reagents via @emmats Lab:

1.5M tris HCl - 1.8g in 5 mL
200 mM DTT - 154.25 mg in 5 mL
25 mM NH4HCO3 - 0.1976 g in 100 mL
50 mM NH4HCO3 - 0.395 g in 100 mL
6M urea - 1.81 g in 5 mL
200 mM TCEP - 286.65 mg in 5 mL
20 mM IAA - 184.96 mg in 5 mL

All of these match up with my calculations except the Tris-HCl. What molecular weight do you have @emmats ? I am calculating to add 1.182g in 5ml

Can you verify my method for making the ACN solvents as well?

Thank you

**Comment by kubu4** [comment]
@Ellior2 - In regards to the Tris solution, you'd be better off using Tris base (it's basic, instead of acidic - the protocol indicates that the solution should be pH = 8.8). This could explain the difference in calculations you.

Also, the methodology you have written up for making solutions is incorrect. Here's an example:
> Dissolve 36.036g Urea into the same 100ml solution

This is wrong because adding the solute to the solvent will increase the volume of your solution. Thus, you will end up with a solution volume greater than 100mL and you will not have the desired final concentration.

For making solutions, always dissolve the solute in the smallest possible volume of solvent. Once the solute has fully dissolved, bring the solution to your desired final volume.

**Comment by Ellior2** [comment]
Yeah, I was thinking about that. I guess I am just unsure how you would "top off" to exactly 5.00ml. I need some guidance on how to make such exact small volumes of solutions.

**Comment by kubu4** [comment]
Options:

- Make larger volume that can be measured more easily (e.g. 50mL)

- Use a measuring device capable of measuring a small volume accurately (e.g. serological pipet)

**Comment by emmats** [comment]
@kubu4  is right, of course, but you can ignore him @Ellior2  for the ~6M of urea. It doesn't need to be so precise so you can just use the numbers I gave you. Unless you want to make things slightly more difficult for yourself!

**Comment by Ellior2** [comment]
Ok. Are you using Tris or Tris-HCl since the pH has to be 8.8? And what is the molecular weight you use to calculate the 1.8g Tris in 5ml? 

Also, can you check my ACN solvent calculations?

Thank you @emmats

**Comment by emmats** [comment]
My notes say Tris HCl. I will follow up with Brook to make sure since there is some confusion. I do not have MW numbers, I just copied what was written on our bottle of Tris. I will double check 1.8 g when I am in the lab tomorrow.

For the ACN solvents the 60% looks good, but the numbers are off a little bit for the 5% (I think you are making a 4.7% ACN and .9% TFA). Note that when you are making these solvents you should not use plastic. Use glass graduated cylinders and for pipetting small amounts (like TFA), don't pipette directly from the bottle (i.e. plastic should never touch your stock reagents). The reagents can erode plastic a little and the plastic particles will be detected in the mass spec.

**Comment by Ellior2** [comment]
Hmmm... I'm not sure where I went wrong. I calculated the two solvents using the same logic.

For the protein quantification part, what concentration of 22 ul of ammonium bicarb are we adding to our 11ul of sample to dilute the urea? 50mM?

Sorry to hammer you with questions.

**Comment by emmats** [comment]
First, updates from Brook: 
Yes, we use Tris-HCl to make our Tris 
Apparently I can't read and it is 1.18 g in 5 mL for the tris

Yes! You are adding the 50 mM. 

I don't mind answering questions. This is better than something going wrong and trying to figure out what it is after wasted time and sample.

**Comment by emmats** [comment]
P.S. generally, don't put plastic pipette tips into concentrated acid.

**Comment by Ellior2** [comment]
Do we need special pipette tips? How do you do it?

**Comment by emmats** [comment]
Not special tips, just use glass as much as possible and pour a small amount into a beaker if you need to use a pipette. That way any dissolved plastic won't accumulate in your stock solution.

**Comment by emmats** [comment]
Brook also wanted me to remind you to make sure you don't overheat the samples during sonication.

**Comment by Ellior2** [comment]
Ok, I'm just going to follow the protocol but I'll be cautious of that. Thank you. I'm going to make some of the reagents tomorrow, the ones that we have chemicals for and won't expire. For the tris-hcl with pH8.8, what should I add if the solution is too acidic? Too basic? And can that be stored on the benchtop?

**Comment by sr320** [comment]
@kubu4 should be able to address any questions re making solutions in lab
tomorrow, I will be available in lab Thursday AM.

Importantly, document everything you do... so someone could reproduce....

**Comment by emmats** [comment]
@Ellior2 , yes it can be stored on the benchtop.

I would add an acid or a base :) Probably relatively concentrated NaOH or HCl. There should be some near the pH meter, I think. @kubu4 can probably be more specific.

**Comment by Ellior2** [comment]
Detailed [sonication](https://ellior2.github.io/Sonication/) steps for review @emmats @sr320 . I plan to do this on Monday if @laurahspencer or @yaaminiv want to help! 

We will need to get dry-ice from the Health Sciences J-wing in the morning. What information do I need to get the dry-ice (i..e. Lab code?)

On Wednesday I plan to do the BCA assay which will set us up nicely for the mini-trypsin digestion starting the 28th.

**Comment by emmats** [comment]
You shouldn't need tongs for dry ice because they have a scoop. You will need the SAFS box number and a Roberts Lab budget number.

Yes, save all sample you don't immediately use at -80.

I usually take a ~500 mL beaker, fill about halfway with EtOH and then add 2-3 pieces of dry ice at a time. Eventually you will see that the dry ice doesn't dissolve fast and that means the EtOH is nice and cold.

At the end of sonicating, I would aliquot the volume you will use for protein quantification so you don't have to thaw the entire sample when you quant it.

I can come by the morning of the 28th to see how things are going. I can stay until about 11:30, if necessary.

**Comment by Ellior2** [comment]
Ok, so aliquot 11ul of each sample into a new tube to freeze for the protein quantification? But then when I start the mini-trypsin, I will only have 89ul. Do I add 11ul of something to get back to 100ul and then determine in step 9 how much of this sample I will need based off of my "new" protein concentration, since I just diluted it?

**Comment by Ellior2** [comment]
Can I just take like 150ul of the supernatant instead of 100ul after the centrifuge step. That way I have enough for the protein quantification AND the digestion?

**Comment by kubu4** [comment]
Heads up on a few things:

1. Most people will be gone from lab on Monday (big sampling at Manchester), so this might not be the best day to run through the proceure?

2. You're [methodology for making the homogenization buffer](https://ellior2.github.io/Sonication/) is incorrect. If your final desired volume is 20mL, then you can't put 20mL of water in a conical tube and add solute to it. Your final volume will not be 20mL. Don't make the solution this way. It's not right and you don't want to establish any bad habits...

3. Make sure to use a plastic container for your dry ice/EtOH bath!

4. Are you processing actual samples? I'd highly recommend going through the protocol with some "practice" samples that are not critical for your experiment if something goes wrong. The [protocol](https://github.com/sr320/LabDocs/blob/master/protocols/ProteinprepforMSMS.md) is still not clearly written in a number of places, so it wouldn't surprise me if you encounter some unexpected difficulties along the way that could ruin your samples.

5. Have you compared the Roberts Lab sonicator to the one that Emma uses in her preps? Are they comparable? Will 10s of sonication be sufficient with our sonicator? Will it be too much?

6. I don't know if we have any clean plastic pestles. You should definitely check this before beginning...

**Comment by emmats** [comment]
@Ellior2 you can sonicate as much of the supernatant as you want.

Hm, I always use a regular beaker for the etoh + dry ice. I haven't had any problems yet, @kubu4 !

**Comment by Ellior2** [comment]
Thanks @kubu4 ! I did facetime with Emma this morning and showed her our sonicator, I think it'll work just fine. I tried sonicating a 100ul water sample in a tube for practice today, and it definitely heated up when sonicating for the full 10 seconds. We decided to cut it down to 5s and since we are doing it three times, we should be good. 

I do have duplicate samples still in the -80C for this experiment and we should have leftover sample too so I am just going to go for it. Otherwise, I'm never going to get these done if I want to run "practice samples" on the MSMS before actually starting to digest mine. 

Here is [updated sonication steps](https://ellior2.github.io/Sonication/)

I'm breaking the whole process down into different steps and I won't pull anything out of the -80C until I know EXACTLY what I am getting myself into that day.

**Comment by kubu4** [comment]
Excellent!

**Comment by Ellior2** [comment]
@kubu4 can you provide me with SAFS box number and Roberts Lab budget number to get dry ice tomorrow? I went with Steven and Holly to a place near the Bagley building where I can get dry ice too. I assume I'll need the same information there.

**Comment by Ellior2** [comment]
Nevermind let me guess... 355020 and 61-0221

**Comment by kubu4** [comment]
Box number is correct. I think that budget number is good, too.

**Comment by Ellior2** [comment]
Also @kubu4 I can't see where the BCA assay kit was put. I see that it came in under the purchasing log, but I don't see it listed on Mychem so I don't know where you put it. I am just hoping to see if there are directions that come along with it so I can be prepared for the next step. Thanks

**Comment by kubu4** [comment]
It's on the shelf with the rest of the kits in 213.

**Comment by Ellior2** [comment]
@emmats 

For the protein quantification, do you do three replicates for each sample, and three replicates for each standard?

**Comment by emmats** [comment]
Yes

**Comment by Ellior2** [comment]
@laurahspencer and I will be starting on the [BCA assay procedure](https://ellior2.github.io/BCA-assay/) tomorrow morning (Wednesday)

**Comment by Ellior2** [comment]
@emmats I've got a few questions for the digestion process I hope to do Monday:

1) For 5 of my samples, I have less than 1ug/1ul of protein, which means that I will have less than 100ug of protein for steps 1-8. For the remaining samples in which I had more than 1ug/ul I am diluting so I have exactly 100ug of protein in the 100ul required starting volume. So at Step 9, can I continue when some of my samples have less than 100ug? Do I just adjust the amount of LysC and trypsin? 

2) Is the process for adding Lys-C the same as the Trypsin process that you described in more detail since they are both (1:30 enzyme:protein). 

From your notes: 
_Prepare the number of trypsin bottles needed (you will want 5 µg of trypsin for each sample, or 1 µg trypsin: 20 µg protein). Add 20 µl water or trypsin buffer to each bottle of trypsin and vortex lightly. Aliquot 5 µl of trypsin to each sample for 100 µg of sample (1:30 enzyme:protein)._

But is it a 1:30 ratio or a 1:20?

3) For the trypsin, I calculated how much I will need based off of the amount of protein in my samples and it looks like I will need 105.4ug so we are 5.4ug short. Can we borrow some from your lab and order more? If I am correct in assuming you add Lys-C in the same concentrations as you would the trypsin, then I would also need 105.4ug, again possibly 5.4ug short. We also haven't received our trypsin and don't know if we will by Monday. It's the last thing we need.

Thank you!

**Comment by Ellior2** [comment]
@sr320 @kubu4 Do we have a 37C incubator in our lab for Step 4?

@emmats Assuming I have enough enzyme to go through with this Monday. Would I be able to use your cold speed vac on Tuesday?

**Comment by sr320** [comment]
Re incubator - yes there is a big one in the corner lab, maybe a smaller one in main lab.
- what size tubes?

**Comment by kubu4** [comment]
@Ellior2 - Actually, we received the trypsin. My fault for not getting it entered on the Purchasing Log. Whoops! Sorry! :disappointed: However, I think I showed you where we stored it - in that drawer in the -20C. 

37C incubator is in the lab with the qPCR machine. There are two. Not sure if either of them is currently turned on. I believe one of them has markings indicating the correct dial position to achieve 37C (the older model). The gray one has a dial with numbers and those numbers can be used relatively accurately to achieve the desired temps. Regardless, you'll need to get them turned on and check their temp a couple of times over an hour or two to make sure the temp is stable, prior to actually putting samples in them.

**Comment by Ellior2** [comment]
@kubu4 Oh I thought you were showing me where you put the Lys-C...but it looks like that is in the freezer. And the Lys-C is only 2ug? Hmmm....

Were we supposed to order [125-05061](http://www.wako-chem.co.jp/english/labchem/product/life/Lys-C/pdf/print.pdf) ?

**Comment by Ellior2** [comment]
Nm... I found Emma's remarks on how to make [Lys-C aliquots]( https://www.evernote.com/shard/s242/sh/d6fc350b-e719-4ea4-9eca-efa8a2cc1c53/77403455192d5345)

**Comment by kubu4** [comment]
I don't know what was supposed to be ordered. I ordered the catalog number @emmats listed in issue #340 .

**Comment by sr320** [comment]
This should list what was ordered
https://docs.google.com/spreadsheets/d/1DHXiiEzWhh0XHnEMvKz4TX10e69ErOWHv5Jo-ouk6x8

**Comment by kubu4** [comment]
@Ellior2, we did get the trypsin, though. It's in the same freezer. Possibly even in the same location as the Lys-c.

**Comment by Ellior2** [comment]
@sr320 Tubes will be 1ml snaptop centrifuge tubes

@emmats when I prepare the Lys-C, do the leftover 20ul aliquots I make belong in the -20C, -80C or neither? What is HPLC grade H20? Is that even more special than nanopure?

Alright I'm done for the night. No more questions lol! Happy Thanksgiving ya'll!

**Comment by emmats** [comment]
For 5 of my samples, I have less than 1ug/1ul of protein, which means that I will have less than 100ug of protein for steps 1-8. For the remaining samples in which I had more than 1ug/ul I am diluting so I have exactly 100ug of protein in the 100ul required starting volume. So at Step 9, can I continue when some of my samples have less than 100ug? Do I just adjust the amount of LysC and trypsin?

**Why do you have so little sample? You had plenty of tissue, right? If you have more tissue, then you need to go back to your original samples and get 100 ug, I think that is the best choice. If you don't have time for that, then start the digestions with the same amount of protein per sample (so go with the lowest amount). You will have to adjust your enzyme amounts.**

Is the process for adding Lys-C the same as the Trypsin process that you described in more detail since they are both (1:30 enzyme:protein).

**I'm not sure what you mean. You add Lys-C as described in the protocol and incubate for 1 hour.**

From your notes:
Prepare the number of trypsin bottles needed (you will want 5 µg of trypsin for each sample, or 1 µg trypsin: 20 µg protein). Add 20 µl water or trypsin buffer to each bottle of trypsin and vortex lightly. Aliquot 5 µl of trypsin to each sample for 100 µg of sample (1:30 enzyme:protein).

But is it a 1:30 ratio or a 1:20?

**Oops - I always do the latter (1:30). I think both will get you good digestion. There is a paper on trypsin amounts and incubate time that I can dig up for you if you're interested in knowing more.**

For the trypsin, I calculated how much I will need based off of the amount of protein in my samples and it looks like I will need 105.4ug so we are 5.4ug short. Can we borrow some from your lab and order more? If I am correct in assuming you add Lys-C in the same concentrations as you would the trypsin, then I would also need 105.4ug, again possibly 5.4ug short. We also haven't received our trypsin and don't know if we will by Monday. It's the last thing we need.

**Sounds like you are ok for trypsin, although @kubu4 overbought for us once so you can always borrow some if you are short. If you do not have Lys-C I can bring some aliquots Monday.**

**Comment by Ellior2** [comment]
@emmats So I definitely have enough protein in the total sample I have sonicated- the problem is that it is less concentrated than 100ug/100ul. So in order to have 100ug of protein for the digestion, I would have to start out with 120-130ul instead of 100ul. The lowest concentration I have is 75.5ug/100ul which means I would have to bring all the samples down to 75.5ug starting protein amount.

I will go ahead and do the 1:30 ratio for the trypsin if that is what we did for the 2015 samples. If we do a 1:30 ratio we will only need 2.5ug trypsin for 75.5ug protein/sample for a total of 55ug for all 22 samples.

From your lab [notebook](https://www.evernote.com/shard/s242/sh/d6fc350b-e719-4ea4-9eca-efa8a2cc1c53/77403455192d5345)
"Made aliquots of LysC (from Wako) following Villen lab protocol (see attached).  Added 450 µl HPLC grade H2O to 2 AU vial.  Made 20 µl (40 µg) aliquots at concentration of 2 µg/µl.  Will add 0.5 µl to each 100 µg sample."

Looks like you are adding 1ug of LysC for every 100ug of sample, hence a 1:100 ratio. In the protocol however it says 1:30...?

I may need assistance getting the incubator fired up in the morning.

**Comment by emmats** [comment]
You should evaporate the samples a bit and then bring the volume back up to 100 µl. Then you will have 100 µg in 100 µl. I'm not sure why your samples have relatively little protein in them. It sounds like you lost a lot and/or did not lyse cells well during the homogenization/sonication. When we did this before we had closer to 2 ug/ul.

Remember, all the details for what we did previously are here: https://www.evernote.com/l/APLBpNYN-VlFvbPyRfi7DbOQX3q2u6s2mbQ
Just follow that for enzyme amounts.

I think I adjusted the Lys C protocol from what the Villen lab does. I now add 3 ug per sample.

I have a 10 am meeting on Monday, but should be able to get to the Roberts lab before 9 to help you get set up. Is that ok?

**Comment by Ellior2** [comment]
Ahhh! I forgot to account for the 22ul of bicarb I added. That should make it better. Let me rework it!

**Comment by Ellior2** [comment]
This is more like it [https://github.com/Ellior2/Ellior2.github.io/blob/master/_posts/2016-11-23-BCA-assay-results.md]

Ok so 3ug of Lys-C per sample and 3ug of Trypsin per sample.

**Comment by Ellior2** [comment]
@kubu4 

Trypsin is not with the Lys-C and no where obvious (to me) in the freezer.

**Comment by kubu4** [comment]
I'll come by in a few minutes to help.

**Comment by Ellior2** [comment]
@kubu4 Did the methanol make it onto the Mychem sheet?

**Comment by kubu4** [comment]
Doesn't look like it. Feel free to add it, if you're so inclined.

**Comment by Ellior2** [comment]
I forgot to order autosampler vials for the MS. Can I "borrow" 22 for tomorrow?

**Comment by Ellior2** [comment]
@emmats 

Here are the [desalting steps](https://ellior2.github.io/Peptide-Desalting/) that I wrote up. Would you mind looking through it and making sure that I have it right- paying special attention to what I am discarding and where my peptides are during each step?

**Comment by emmats** [comment]
Just bring your samples in tubes down to UWPR on Monday and we can use their autosampler vials. They are included in the MS pricing. 

Desalting
Step 2 - You can discard the liquid at the bottom of the columns every other addition of solvent A (it easily fits 400 ul at the bottom)

Step 5 - I always keep the salt fraction in case something goes wrong. I did have to go back to my salt fraction once when I used the wrong desalting columns.

Step 8 - this should be 0.1% formic acid! Thanks for finding that typo in my protocol.

**Comment by kubu4** [comment]
A couple of things to add to this:

- The spin steps are listed in RPMs instead of RCF. RPMs result in different RCF depending on which centrifuge is used. For example, we have three different centrifuges in the lab. If you spun the same sample at 2000RPM in each of those centrifuges, each centrifuge would apply a different amount of force (RCF) to the sample.

As such, if utilizing RPMs, the centrifuge model should be listed. Otherwise, use RCF instead, which can be easily set, no matter which centrifuge you're using.

- The columns are on the shelf with all the kits in FTR213. They're in a big plastic bag.

**Comment by emmats** [comment]
@kubu4 the exact speed/force doesn't matter that much, as long as the liquid is pushed through.

**Comment by kubu4** [comment]
@emmats In this particular instance, sure. However, for other applications requiring a centrifuge, it's important information. So, it's only proper to be consistent; for reproducibility sake.

**Comment by Ellior2** [comment]
@emmats I made the solvents for desalting taking extra care to minimize plastic contamination and stored them in glass containers. Now that I have them made, can I pipette directly out of my working bottle since it is more dilute or should I keep pouring off little amounts into beakers to pipette from?

**Comment by emmats** [comment]
That is fine. Although I usually make smaller bottles (100-200 mL) to pipette from, which is generally a good practice. You don't want to pipette directly from large bottles of reagents because you could easily contaminate the whole jar.

**Comment by sr320** [comment]
@Ellior2 is it safe to say that the knowledge from this 75+ commented issue has been incorporated into? 

https://github.com/sr320/LabDocs/blob/master/protocols/ProteinprepforMSMS.md

**Comment by Ellior2** [comment]
@emmats Thanks, I had only made 150 ml of each reagent.

@sr320 It is documented pretty well in my online lab notebook, but I will work on incorporating it all into the master protocol. It will probably end up becoming a 10 page document if that is what you want.

**Comment by Ellior2** [comment]
Whew! I finished! This thread is almost over I promise... 

One more question for @emmats : During some steps you explicitly say to vortex and some you do not. For example, it is stated in the digestion protocol to vortex after the DTT addition but not after the IAA addition. Is there reason for this? Could vortexing when it's not needed potentially ruin your sample?

**Comment by emmats** [comment]
Assume vortex when it seems logical. It will not ruin your sample.

**Comment by Ellior2** [comment]
For @yaaminiv and @laurahspencer coming up on your extractions- I believe all you need to order is more trypsin.

**Comment by kubu4** [comment]
Bringing this back from the dead. :dead:

I think the [protocol](https://github.com/sr320/LabDocs/blob/master/protocols/ProteinprepforMSMS.md) should list vendor and catalog numbers for stock reagents.

I also think it would be helpful to list needed equipment at the beginning of the protocol. Possibly indicate if equipment is available in Roberts Lab or if it's externally accessible (and where/who's lab).

**Comment by Ellior2** [comment]
Alright, I think I've added most of the necessary equipment. Feel free to add and update @laurahspencer @yaaminiv

**Comment by Ellior2** [comment]
I added the things we recently bought and listed the vendors and catalog numbers. I searched for some of the ones we already had in the purchasing log- couldn't find them. I looked them up on Mychem and added the quantity we bought and from what vendor. I could not find the cat. # on those however.

**Comment by Ellior2** [comment]
@kubu4 Please order more MS autosampler vials. I guess they are not longer included in the price of the MS rental. We ended up taking a full unopened box and so we will need to replace it. I will bring back the remainder of the box I am using.

[MSCERT5000-33TR ](https://www.thermofisher.com/order/catalog/product/CERT4000-993)

It's also listed on the protocol :wink:
