### ISSUE TITLE
Try Assembling Oly Genome w/ Platanus

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#334]
via Katherine

>I spoke to a friend of mine who has assembled some butterfly genomes from mate-pair libraries. She recommended the platanus suite as it is easy to use and supposed to be good for heterozygous species. The authors actually tested this program on the gigas genome. Based on what is listed on github, it looks like you have:

Raw data for all libraries (received 20160127)
scaffold.fa.fill, Initial genome assembly of unknown parameters (rec' 20160314)
*fq.gz.clean.dup.clean.gz, Filtered data from the 500, 800, and 300 insert size libraries (rec' 20160512)
Ostrea_lurida.scafSeq, assembly of 300, 500, and 800 insert libraries
So if this is something you want to pursue apart from BGI, I think the approach would be:
1) the libraries that haven't been filtered yet would need to go through the platanus_internal_trim program (insert sizes 5000,10000,5000,10000,2000), 
2) use the small insert libraries for config assembly, 
3) perform scaffolding with the contains and large insert size libraries, 
4) gap-closing with the scaffold and smaller insert libraries

**Comment by sr320** [comment]
Data @ 
https://github.com/RobertsLab/project-olympia.oyster-genomic/wiki/Genome-sequencing-September-2015

**Comment by seanb80** [comment]
I installed VMWare and Platanus on hummingbird. Am currently transferring over the small insert libraries from Owl and will begin assembly as soon as they're moved/unzipped.

**Comment by seanb80** [comment]
In trying to assemble these, it appears that one of the .gz files on Owl may be corrupted, specifically 151118_I137_FCH3KNJBBXX_L5_wHAXPI023905-96_1.fq.gz. I've tried re-copying from Owl, multiple unzip applications, and both linux and OS X based unzip.

Do we have a backup anywhere that I could try or any other suggestions?

**Comment by kubu4** [comment]
Can you clarify on why you think it's corrupted (i.e. are you getting some sort of error message during unzipping, or is the program failing to recognize the file format)?

To verify file integrity after transfer, you can check the MD5 checksum hash value. The source folder on Owl should have a file called ```checksums.md5``` with the original hash values for each file. After transfering the file(s), generate a MD5 checksum on the file and compare it to the value listed in the ```checksums.md5``` file. If they match, the file transferred successfully (and is not corrupted due to the transfer process).

Alternatively, you can try grabbing a backed up version of the file from here: 

https://drive.google.com/file/d/0BzKkDWZ6tIK4eXVYN2UzZnlqRWs/view?usp=sharing

**Comment by sr320** [comment]
Related- It is probably a habit to get in to runing MD5 checksum when moving large sequence and confirm integrity.

**Comment by seanb80** [comment]
I will start running MD5 hashes after transfers. 

As far as the error, gunzip provides a generic "data stream error" with no associated error code. Some googling suggests this is due to a corrupted gz. 

The MD5 hashes did not match between the transferred file and the checksum.md5 file, and when I tried to retransfer once more, md5 returned the same, incorrect hash.

 I will try the google drive.

**Comment by sr320** [comment]
Try running Md5 on file on owl- should match Sam's hash

**Comment by kubu4** [comment]
@seanb80 , you're going to want to strangle me. Use this link instead of the one I provided above: https://drive.google.com/file/d/0BzKkDWZ6tIK4R2RLWkpjdHBOdkE/view?usp=sharing

Sorry! 

The difference is:

- The link I sent you initially, is from a copy of that file that exists in different directory than the "source" directory (which I didn't realize when it popped up in the Google Drive search results).

- The second link is the original file downloaded from BGI (the company that performed the sequencing).

**Comment by seanb80** [comment]
Just did an MD5 on the Owl copy, as well as the first google drive copy, both the same, while different from the listed MD5. Will download this new link and cross my fingers.

**Comment by seanb80** [comment]
No luck, all versions have the MD5 hash: 

f10c1f143d153f364cf6be13452eea4a

while the checksum.md5 file has the hash: 

08cfdc6fdc5a6190cb05cdcb81fa5b9c

They all also produce the same data stream error upon unzipping.

**Comment by kubu4** [comment]
Yep, I see the same... Hmmm... Let me see if I can re-download from BGI...

**Comment by kubu4** [comment]
I've spot checked a bunch of others and they all seem OK. @seanb80 have you noticed issues with any other files?

**Comment by seanb80** [comment]
I have not, all other short insert reads have worked perfectly.

**Comment by kubu4** [comment]
Doing some continued testing, but here's my notebook entry for when we originally received the files. I generated a MD5 checksum and compare that to the MD5 checksums provided by BGI; they all match.

Also, @sr320 possibly discovered that the 66_1 sample is also faulty. Maybe he can provide notebook link to confirm?

**Comment by sr320** [comment]
https://sr320.github.io/student-fish546-2016/oly-read-check/

**Comment by sr320** [comment]
Can we proceed without the corrupt files?

**Comment by seanb80** [comment]
We can, and have! Platanus doesn't offer any sort of eta, but I'll update this when it's done.
