### ISSUE TITLE
Access to plate reader for BCA assay

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#352]
What are the options for plate readers with regard to doing the BCA protein assay?

**Comment by kubu4** [comment]
Possible options (but not certain - will require physically checking the machines):

- @emmats lab
- Seeb lab
- Hauser/Naish
- Roberts Lab NanoDrop (less than ideal due to progression of sample color change between measurements)
- Roberts Lab Qubit (similar to NanoDrop - plus need to see if using BCA is feasible)

**Comment by emmats** [comment]
We have a plate reader. Ask Brook about using it as it is finicky and Rhonda may need a guiding hand. Also, all of these instruments are MacCoss lab, but Mike doesn't care if we use them for collaborations. But if Rhonda will be in our lab a bit Genn (research scientist/lab manager) may want to chat with her.
