### ISSUE TITLE
Oly Bisulfite Sequencing 

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#36]

**Comment by sr320** [comment]
next week

**Comment by sr320** [comment]
url?

**Comment by sr320** [comment]
Specs look good

**Comment by sr320** [comment]
@kubu4 take these libraries are a no go based on Bioanalyzer?

**Comment by kubu4** [comment]
I didn't have a chance to look at all the sample closely. I sent the file to @jheare to look at in more detail. I'll try to look at it more thoroughly this weekend.

**Comment by sr320** [comment]
@jheare so what's the story with http://heareresearch.blogspot.com/2015/02/2-17-2015-bioanalyzer-results-for-bs.html

Why is there no DNA?

ps Notebook entry should include some reflection if not as expected - that is, what will be changed when done again...

**Comment by jheare** [comment]
No clue. Sam and I discussed it the other day, Sam seems to think it's a
kit issue. We both ran the same kit on the same day on independent samples
and we both got nothing back. I've got some leftover bs converted DNA that
I could quantify to see if the problem is in the library process or the bs
conversion. Otherwise, I'm not sure how to proceed.

**Comment by kubu4** [comment]
Technically, we have different problems. I don't have any issues with library yield.

My issue with the kit is a high degree of adaptor contamination that appears to be carried through the procedure.
