### ISSUE TITLE
Fix -80 alarm

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#386]
December 12, 2016 at 01:10PM<br>
created via Do Button

**Comment by kubu4** [comment]
What needs fixing?

**Comment by sr320** [comment]
Get phone call after the alarm is no longer going off- not when it sounds

**Comment by kubu4** [comment]
I'm pretty sure there's a delay built in between when the alarm initializes and when the Sensaphone dials out. This is to prevent phone calls happening every time someone has the door open for a minute or two (which generally triggers the alarm). Otherwise, we'd get frequent "false alarms".

Also, I'm assuming the alarm on the freezer is being manually muted? If yes, then the alarm condition is still in effect (i.e. temp reading is too high), but the alarm is no longer going off. 

These two factors would explain why we get phone calls after the alarm is no longer sounding.

I'm guessing this is the situation that triggered the most recent alarm call?

We can eliminate this delay, if desired.

However, if the alarm is no longer sounding on its own (due to the fact the temp has returned to normal range), then the Sensaphone should not be calling and something is screwy.

**Comment by sr320** [comment]
The latter, something is screwy. (also it was Claire's old freezer, which
we cannot seem to mute).

**Comment by kubu4** [comment]
Gotcha. I can't remember if we wired that freezer or someone else did, but I'm guessing it's related to the wiring to/from the Sensaphone and that freezer (e.g. wired to "normally open" circuit designation instead of "normally closed").
