### ISSUE TITLE
Preparing for Pub-a-thon 2017

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#400]
With pubathon only a few weeks away there are a couple of things we could go ahead and get moving. One is the consideration of writing platforms. I am open to suggestions but the platforms that come to mind.
* Google Docs
* Overleaf
* GitHub
* Authorea/ Github

Related to this, is the second consideration- paper/reference management. I given the overlap I really would like to develop a communal repository of papers, ideally with the ability for everyone to mark up. Then, how do we handle citations? A few ideas
* Paperpile (Docs)
* Zotero
* http://f1000.com/work

Please add thought, suggestions, and questions. This could be the best. Pub-a-thon. Ever.

**Comment by sr320** [comment]
@grace-ac Can you set up a mock set of papers (ones we might read  / cite) using the mentioned platforms and we can start test. maybe jus 3-4 papers. Feel free to try other platforms

**Comment by sr320** [comment]
I am thinking triple bonus points for anyone who can get all the way to submision without using Word.

**Comment by jldimond** [comment]
First Excel and now you want me to give up my beloved Word?! But hey, I'm all about the points. I wasn't crazy about Authorea...I'd be more inclined to go with Google Docs (it is more Word-like 👍)

**Comment by grace-ac** [comment]
Do I just pick out any four papers? Not entirely sure what to do for this... @sr320

**Comment by sr320** [comment]
Any four.
Create zotero group.
Is there a way to collaborate with paperpile?

**Comment by grace-ac** [comment]
I will look into that! Thanks

**Comment by sr320** [comment]
Also explore http://f1000.com/work

And see what that is all about - thanks!

**Comment by kubu4** [comment]
What about Mendeley for a group paper repository? I know we have/had a group in the past, but I can't remember if we liked it or not. I think Mendeley formats refs, too...

**Comment by grace-ac** [comment]
I've been looking at the f1000 workspace and it's pretty cool
you can add papers directly to it when you search them on the web. there's a google docs add on like paper pile that formats refs as well.

i don't know anything about mendeley... but i can look into it!

**Comment by grace-ac** [comment]
f1000 also has a desktop extension that allows you to upload pdfs for commenting, etc. in f1000. there's also a word add-in.

**Comment by sr320** [comment]
Useful guide

http://guides.lib.uw.edu/research/citations/citation-tools

**Comment by sr320** [comment]
Neat feature of F1000

![img_0074](https://cloud.githubusercontent.com/assets/4442039/21649041/25899f38-d255-11e6-8cbb-328be0bf59ff.PNG)

**Comment by sr320** [comment]
Open Science Framework is a cool option - 
See https://osf.io/3xf6m/

Based on meetings yesterday I think each paper will have it own repo (OSF is an option) even if actually written somewhere else.

We need to try to capture ALL aspects of the process as we learned from dealing with revisions yesterday

**Comment by seanb80** [comment]
Something to consider on the collaborative writing front. I've been playing with [Fidus Writer](https://www.fiduswriter.org) for a little bit and it might work. 

It supports inline commenting, and seems to have good bibliographic support (takes bibtex code from whatever paper manager you like) as well as has decent figure support. Also, it can save output in multiple ways including ODT, LaTeX, and docx.

One thing it doesn't have currently is revision tracking, so that might be a show stopper. 

You can play with it on their server by using the Try Fidus Writer option, or I've set up a server temporarily which can be accessed at http://128.95.149.195:8000

**Comment by grace-ac** [comment]
Looks like I may need people's email addresses, but here are links to the various platforms for paper citations/management. There are some random papers in each, so we can see what might work best with sharing notes on pdfs, adding references to the shared folder, etc. 

And if you want to look around at how the different formats use word or google docs, we can make mock papers to try that out as well. I know PaperPile, RefWorks, F1000 go through google docs and have add-ons where you can format citations within google docs which is pretty sweet. 

Everyone participating will have to make accounts for each of these platforms. 
There are extensions for these platforms, which I recommend because they make adding papers to way way easier! 

- F1000: http://f1000.com/work/#/items?collection=125449
- Mendeley: https://www.mendeley.com/community/88fe00d2-cf3d-3e7a-98d4-502aa8763ba1/
- PaperPile: https://paperpile.com/shared/v5MC3z
- RefWorks: https://refworks.proquest.com/library/586d6e0ee4b00198145b6c39/
- Overleaf main site: https://www.overleaf.com/ (I just linked with my google account - didn't look to  much into it, but it looks a bit more involved than the other ones in this list. Check it out)

Zotero is being weird for me, so I'm still trying to get that one going. And I haven't looked at EndNote yet, but I think Laura said she uses that one, so we can check that out, too. 

It may be easier if I just invite you guys by email after you make accounts.

**Comment by sr320** [comment]
Re Refworks is there a code ?

**Comment by grace-ac** [comment]
@sr320 not sure what you mean by code. code to use it?

**Comment by sr320** [comment]
See the screenshot?

**Comment by sr320** [comment]
![img_0077](https://cloud.githubusercontent.com/assets/4442039/21661291/3bf01e7c-d288-11e6-96b8-a558a84dc262.PNG)

**Comment by grace-ac** [comment]
oh weird! no i didn't have to use one. i just had to use my UW email address and then I was able to search UW. Then it said that UW uses RefWorks and then I could make an account.

**Comment by grace-ac** [comment]
you select "Create and Account" rather than "Log in with University's credentials"

**Comment by kubu4** [comment]
On the Zotero front, there's already a Roberts Lab group: https://www.zotero.org/groups/295352

I think @sr320 is the group admin and will have to invite people (assuming we want to use this).

**Comment by kubu4** [comment]
Here's quick summary of my thoughts on the reference managers (as a Mendeley user):

#### F1000
- Requires browser extension
- No offline reading
- Good options for importing library from other services
    - includes selective importing (i.e. don't need to import an entire library)
- Can't resize columns
- PDF annotation is cool
- Group access = $300/yr?

#### Paperpile
- Works only in Chrome (bad if you're using outdated version of OSX, which Chrome no longer supports)
- No alternative viewing options
- Requires browser extension
- Good importing, but no selective importing from a given library
- Sync w/Google Drive is cool
- Maintains imported folder structure and tags!

#### RefWorks
- No add-ons/extensions needed
- Is this linked to UW (e.g. do you lose access to your stuff once you leave the university)?
- Library imported limited to Mendeley
- No alternative viewing options

#### Zotero
- Works w/Authorea for citations
- Storage limits
- Cannot import libraries via web; requires standalone client
- Only imports from .bib files
    - Loses folder structure
    - No tags synced to web?

**Comment by kubu4** [comment]
I might be making the switch to using Overleaf as my writing platform. The built-in templates are a major draw...

Plus, there is a way to perform offline editing: https://ineed.coffee/3454/how-to-synchronize-an-overleaf-latex-paper-with-a-github-repository/
