### ISSUE TITLE
Try improving Bismarck mapping rate

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#402]
Try tweaking some parameters to improve rates of mapping for Hollie oyster data

See http://www.epigenesys.eu/images/stories/protocols/pdf/20120720103700_p57.pdf

For considerations.

**Comment by seanb80** [comment]
I have a script running that should test a few different things. First, it will test if there's a difference between Trimmomatic (which Hollie used in her analysis) and Trim Galore. The developer for Bismark claims there is, so it seemed worth a shot. Also, it should test if there is a difference between different values of N in bismark, where N is the number of allowable mismatches. 

Most of the Low Mapping Efficiency advice in that paper pertains to Paired End alignments, which we don't have, but I found a thread on SEQanswers.com where the developer for Bismark answers questions, so if none of this works, that's my next stop. Just need output information from Bismark first!

**Comment by seanb80** [comment]
Update: N value for Bismark/Bowtie has no real effect on mapping efficiency. Trimming program has some effect (~1%) but I cannot at this moment explain if that's an artifact of slight variance in settings or some functional difference between trimming programs. Have BSMap downloaded/installed and will run that tonight to see if it produces different results/behaves properly with regard to contig usage.

| % mapping efficency | N = 0 | N = 1 | N = 2 |
|---------------------|-------|-------|-------|
| Raw Data            | 2.4%  | 2.4%  | 2.4%  |
| Trimmomatic         | 2.8%  | 2.7%  | 2.7%  |
| Trimgalore          | 3.8%  | 3.8%  | 3.8%  |

Notebook entry: http://rpubs.com/seanb80/236936

**Comment by seanb80** [comment]
Update with BSMap results: BSMap provides better mapping rate, 13% for the Trim Galore trimmed sample, 11% for Trimmomatic, and 9.7% for raw data. 

There's a paper that looks at read length effects on mapping efficiency, and it shows that BSMap is better for shorter read lengths than Bismark, so that might be a cause for that. [paper](https://www.hindawi.com/journals/abi/2014/472045/)

![472045 fig 008](https://cloud.githubusercontent.com/assets/10619258/21485090/09ece08c-cb52-11e6-8b19-34668ed314ed.jpg)


![screenshot_2016-12-26_08-57-31](https://cloud.githubusercontent.com/assets/10619258/21485022/3c229520-cb51-11e6-915c-a8d94e0514b0.png)
![screenshot_2016-12-26_09-25-33](https://cloud.githubusercontent.com/assets/10619258/21485024/3da51e86-cb51-11e6-9d44-fa1d95251ad0.png)
![screenshot_2016-12-26_09-51-56](https://cloud.githubusercontent.com/assets/10619258/21485026/3f5970ec-cb51-11e6-8116-c6664a62520f.png)

**Comment by hputnam** [comment]
Yes, I had much higher mapping with BSMap than Bismark, but no data from scaffolds >9999 with BSMap. Is this still a problem?

**Comment by seanb80** [comment]
I'm re-running it in verbose mode to have more to work with, but what exactly should I look at to check scaffolds used vs. expected?

**Comment by hputnam** [comment]
When viewing all genome scaffolds on IGV and adding in the BSMap results the methylation data from BSMap stopped at scaffold 9999. With Bismark we now get data across all scaffolds. I will look to see if I have any images.

**Comment by seanb80** [comment]
Talked to Steven today, looks like BSMap may have worked, as we were able to visualize all contigs for both BSMap and Bismark outputs. I can post pictures if you would like. 

Here is a link to the GitHub for the fork of BSMap I used. It's version 2.90, and it looks like somewhere in the past few versions they increased the number of addressable contigs from 2<sup>13</sup> to 2<sup>17</sup>, so that may have fixed the problem? [Github](https://github.com/zyndagj/BSMAP)

**Comment by seanb80** [comment]
On the support front,  there's a guy who's picked up BSMap after it's googlecode repo went away, but from his GitHub it looks like a solo thing, with pretty infrequent updates. 

The dev for Bismark still posts regularly on SeqAnswers, so if I had to guess I'd say that Bismark will have support for longer. 

I'm down to try both, for the upcoming data, and can work BS Seeker in as well, so we can compare.

**Comment by sr320** [comment]
I think the general plan going forward, is have all three pipelines running
and available.
Then compare and contrast the results.
