### ISSUE TITLE
GeoProt Paper submission final steps

### ISSUE THREAD

**Issue by grace-ac** [sr320/LabDocs#415]
ideas on suggested reviewers? @sr320 

emma suggests 3-5. she will be thinking of a couple as well.

**Comment by grace-ac** [comment]
ideas from emma:
Pierre Boudry, IFREMER
Nolwenn Dheilly, Stony Brook University

**Comment by sr320** [comment]
Do they require suggested reviewers?

**Comment by sr320** [comment]
Ximing guo
Jerome La Peyre
Gary wikfors


On Tue, Jan 3, 2017 at 1:43 PM Steven Roberts <sr320@u.washington.edu>
wrote:

Do they require suggested reviewers?


On Tue, Jan 3, 2017 at 1:41 PM grace-ac <notifications@github.com> wrote:

ideas from emma:
Pierre Boudry, IFREMER
Nolwenn Dheilly, Stony Brook University

—
You are receiving this because you were assigned.


Reply to this email directly, view it on GitHub
<https://github.com/sr320/LabDocs/issues/415#issuecomment-270232702>, or mute
the thread

**Comment by grace-ac** [comment]
yes they do- i just checked and it says 5 to 8 suggested reviewers and their emails are required.
