### ISSUE TITLE
Emu connection status

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#457]
I cannot (nor Rhonda) ssh into Emu. But it is online and operational when sitting in front of it. 
@seanb80 do you know what this issue is here? I believe you said you could not connect either this AM?

Thanks

**Comment by kubu4** [comment]
Any error messages?

**Comment by sr320** [comment]
Connection establishment timeout.

**Comment by kubu4** [comment]
Can't get in from home; same issue.

**Comment by sr320** [comment]
Odd - three days ago everyone could ssh in. It is a static IP, could
firewall be set at UW level?

**Comment by kubu4** [comment]
Not UW (I just ssh'd into my computer).

None of the cluster computers are accessible via ssh. Possibly a bad/dead switch?

**Comment by kubu4** [comment]
Can you try to use Remote Desktop to access one of the other cluster Macs?

**Comment by sr320** [comment]
Cannot Remote into Hummingbird
(but can genefish)

**Comment by kubu4** [comment]
OK. That definitely lends additional support to the bad switch idea...

**Comment by kubu4** [comment]
Or maybe the entire cluster is turned off? 

I ssh'd into Ostrich earlier today while at work, so something happened between noon and now. I know Jon Wittouck was poking around looking for UW inventory tags. Possible he accidentally knocked a power cable out?

**Comment by sr320** [comment]
At 12:15 I checked remote and sitting in front of.

**Comment by seanb80** [comment]
I'm unable to ssh in to Emu (or anything) due to blocked ports on the connection I was using, I was on Emu yesterday and everything was working however.

**Comment by kubu4** [comment]
OK, here's the deal. IP addresses for all four "cluster" computers (Emu, Hummingbird, Ostrich, Roadrunner) have been changed. I've updated the [Roberts Lab Computers spreadsheet](https://docs.google.com/spreadsheets/d/1mtIITcjqZVEQtynYZFdOdx51uXTiXP7Jvvzv_SnWCDY/edit#gid=0) with the new IP addresses.

HOWEVER! This does not resolve the issue of remote access!

I suspect these new IP addresses are related to the email Michael Parker recently sent out regarding converting computers to have IP addresses that are only accessible via the UW network (e.g. IP addresses that are not publicly accessible outside of UW).

@sr320, do you want to speak to Michael Parker about this or should I contact him?

This is particularly frustrating due to the fact that there was absolutely no notice about this change taking place, without discussing the impacts with us first.

There's also a remote (no pun intended) possibility that the UW is simply blocking the standard SSH port (port 22) on these new IP addresses. I'll try changing the default SSH port on one of the computers, test out remote access, and report back shortly.

**Comment by sr320** [comment]
To confirm - this only impacts ssh?

Lets determine options / huskynet before I check with Parker. My guess is
he would have told us.

**Comment by kubu4** [comment]
I can't try screen sharing, as I'm currently on the UW network, nor do I have a Mac at home to test. However, screen sharing should still work for Mac-to-Mac connections. I have not investigated options for screen sharing Mac-to-Linux (e.g. Mac-to-Emu).

Although changing default SSH ports did not work, I did discover something that allows SSH to work! 

It turns out that the IP addresses that are shown when you Google "what's my ip" are somehow different than what's assigned by the university (or something). The "alternative" IP addresses have been added to the [Roberts Lab Computers spreadsheet](https://docs.google.com/spreadsheets/d/1mtIITcjqZVEQtynYZFdOdx51uXTiXP7Jvvzv_SnWCDY/edit#gid=0) and all of them work with SSH.

To view a computer's IP address (instead of Googling "what's my ip"), use the following command:

`ifconfig | grep broadcast`

I'm going to close this issue and, in the interim, will look into huskynet to try to understand if it will work with Terminal.

**Comment by kubu4** [comment]
Well, those "alternative" IP addresses only work on the UW network...

Need to talk to IT or Michael Parker to get remote (i.e. off-campus) access to these computers.

**Comment by sr320** [comment]
Huskynet will work though?

**Comment by kubu4** [comment]
I don't think so. As far as I understand, it's for being able to access UW websites that normally require you to be on the UW network to fully use (e.g. the libraries for accessing UW subscriptions - even though they have their own off-campus log-in service).

Additionally, HuskyOnNet is not available for Linux.

**Comment by seanb80** [comment]
I just tested HuskyOnNet on my MacBook and was able to connect to Emu using the 172.* IP address over both SSH and an R-Studio Server connection, using an LTE connection, so it looks like that's a route around the inaccessibility of the 172.* IP block to the external internet. 

There's still the problem of the lack of support for i-devices with HuskyOnNet however.

**Comment by kubu4** [comment]
That's cool. Thanks for testing that.

From a personal perspective (i.e. someone who connects from a Linux system), I vote to contact IT/Michael Parker to obtain accessible IP addresses for all four units.

Additionally, a HuskyOnNet login is valid for a maximum of 72hrs before it resets. I have certainly been connected to one of those four computers for longer than that (using a computer at home), so this limitation is also a potential argument for obtaining accessible IP addresses from the university.

**Comment by sr320** [comment]
Why not just change to IP back to what it was?

**Comment by sr320** [comment]
I am going to close. 

I do not see the current state (using Huskynet) an issue. 
I could be convince later on this needs a solution (critical need for remote access).

(I believe all the pub-a-thon products can be finished without ssh 😃 ) 

also SAFS will not provide sanctioned Linux solution. 

Also, hopefully we will be using Hyak soon....

**Comment by kubu4** [comment]
I'm realizing I'm a bit of a control freak; I couldn't let this go. I emailed Michael Parker and got publicly accessible, static IPs assigned to all four computers, and configured all four computers to use the new IP addresses. The new IP addresses have been updated in the [Roberts Lab Computers spreadhsheet](https://docs.google.com/spreadsheets/d/1mtIITcjqZVEQtynYZFdOdx51uXTiXP7Jvvzv_SnWCDY/edit#gid=0).
