### ISSUE TITLE
DIA Analysis: settings for the Protein Digestion Simulator

### ISSUE THREAD

**Issue by laurahspencer** [sr320/LabDocs#483]
@emmats I used the Protein Digestion Simulator, but I'm curious if you suggest changing any of the settings. I modified the input file settings, but I used primarily the default settings: 

![settings 1](https://github.com/laurahspencer/LabNotebook/blob/master/images/2017-02-12_Digest-Settings1.png?raw=true)

![settings 2](https://github.com/laurahspencer/LabNotebook/blob/master/images/2017-02-12_Digest-Settings2.png?raw=true)

![settings 3](https://github.com/laurahspencer/LabNotebook/blob/master/images/2017-02-12_Digest-Settings3.png?raw=true)

![settings 4](https://github.com/laurahspencer/LabNotebook/blob/master/images/2017-02-12_Digest-Settings4.png?raw=true)

**Comment by emmats** [comment]
Please see Sonia's tutorial on PECAN (link provided in the wiki entry). I believe she details which settings should be used.

**Comment by sr320** [comment]
Couple things here...

I do not see info on DIA wiki regarding using Protein Digestion Simulator.

I do not see anything in Sonia's tutorial on Protein Digestion Simulator.

**Comment by emmats** [comment]
This is what happens when I try to answer questions on the weekend :)
You're right, I was mistaken: Sonia has instructions for MSConvert, not for the protein digestion simulator. See below for the settings I used.
<img width="680" alt="screen shot 2017-02-13 at 8 47 02 am" src="https://cloud.githubusercontent.com/assets/4564812/22892925/0a73288e-f1c9-11e6-916c-e689c89e7d2b.png">
<img width="677" alt="screen shot 2017-02-13 at 8 46 54 am" src="https://cloud.githubusercontent.com/assets/4564812/22892927/0ed11a76-f1c9-11e6-877f-b7e2c6ee785b.png">

**Comment by sr320** [comment]
Thanks!
Laura and Yaamini - Please spend some time getting the DIA protocol flushed
out before diving too far in.
