### ISSUE TITLE
DDA / Abacus on 021417 files

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#492]
@seanb80 might already have this - but if not can you please fix all of my errors in trying to get Abacus to complete on Rhonda's files. As you are aware I have the two parameter files in that directory as well as the starting files. 
If you could post the Abacus tsv here, that would be great - thanks

**Comment by seanb80** [comment]
Re-running the samples now! will upload the .tsv file when they're done.

**Comment by seanb80** [comment]
Here is the .tsv file from running Abacus using the ABACUS-01.param file.

[ABACUS_output.tsv.zip](https://github.com/sr320/LabDocs/files/784124/ABACUS_output.tsv.zip)

**Comment by Ellior2** [comment]
Thanks Sean! I was looking over the file... and for some reason I don't see the data for sample 20A. I only have 43/44 samples there.

**Comment by seanb80** [comment]
It looks like something went wonky with the Comet run on that particular sample, I'll try to re-run Comet and Abacus tonight, and upload the fixed results when they're done.

**Comment by Ellior2** [comment]
Also @emmats I'm trying to get my header to look like this....
![image](https://cloud.githubusercontent.com/assets/20071030/23373334/666d7a34-fcd4-11e6-814d-1d8b0375e9a9.png)

But how do you differentiate between your samples when you can only use 0's and 1's? I've renamed my samples to be integers between 60-103 to eliminate the letter "A" I have used to indicate the duplicate run.

This is what mine looks like when I bring my tab-delimited txt file into Excel for ease of viewing.
![image](https://cloud.githubusercontent.com/assets/20071030/23374319/9f8b44d2-fcd8-11e6-9561-3a4933fa7a13.png)


I tried to upload the [txt file](https://github.com/Ellior2/Fish-546-Bioinformatics/blob/master/analyses/DDA_2016/Abacus_Sean.txt) that I converted from the tsv file from Sean into Qspec and it won't register the file in the upload cell.
![image](https://cloud.githubusercontent.com/assets/20071030/23374412/1067c45a-fcd9-11e6-9f53-eb14435f9295.png)

It is 1MB.

**Comment by kubu4** [comment]
Hmm, that's weird. I just downloaded your file and used the [Qspec](http://www.nesvilab.org/qspec.php/) "Browse" button and was able to successfully get the file ready for upload:

![qspec_spectral_counter](https://cloud.githubusercontent.com/assets/4514104/23375915/fa989018-fcde-11e6-9af9-c5dd97eef7a5.png)


Possibly try a different browser?

**Comment by kubu4** [comment]
The following items are not related to your issue, but caught my attention.

I noticed this:

>that I converted from the tsv file from Sean

@Ellior2 - Do you have a notebook entry detailing this? It shouldn't require any "conversion", as a TSV file is a tab-separated values (i.e. tab-delimited) file already.

I also noticed this:

> I've renamed my samples to be integers between 60-103

@Ellior2 - Do you have a notebook entry detailing this? How did you perform this?

If anyone is wondering where I'm going with this, there are two concerns:

1. Lack of documentation. It's hard to help if we can't see what has been done to arrive at this stage.

2. Potential use of spreadsheet software to handle intermediate files. This has potential to cause major issues and should be avoided at all costs! 

Many spreadsheet softwares can/will attempt to interpret the type of data in a cells. Although this can be a handy feature, it can also result in changes to your data. For example, Excel has a propensity to change certain number formats to dates. Additionally, numbers may get rounded off. 

Here's a reference for examples of real-world problems caused by using Excel in biological data sets: [Mistaken Identifiers: Gene name errors can be introduced inadvertently when using Excel in bioinformatics](http://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-5-80)

**Comment by emmats** [comment]
You can only compare to sample types at once because you are limited to column headers of 0 and 1 . You just need to make note of the order of your columns somewhere else to know what order they are in. I usually rename my columns as soon as I get the qspec results back so I can easily keep track of them. 
Sorry for slow responses. I am at a conference this week.

**Comment by emmats** [comment]
that should be TWO sample types, not "to"...

**Comment by kubu4** [comment]
@emmats - Can you clarify this? Do you mean you can only have two samples per file? Or, does the program compare adjacent columns of 0 and 1?

Do you have an example file of the original Abacus output file and an example of that same Abacus file formatted for entry into Qspec that we could look at?

**Comment by sr320** [comment]
Here is an example input
https://github.com/sr320/LabDocs/issues/471#issuecomment-279855252

**Comment by kubu4** [comment]
I can't seem to retrieve that example file (EFvsLF.txt). Connection keeps timing out. Any chance it's hosted somewhere else?

**Comment by kubu4** [comment]
Actually, hold that thought... Sorry.

**Comment by kubu4** [comment]
Nope, can't get it for some reason.

**Comment by emmats** [comment]
Here is a file for qspec and its corresponding abacus file. there is a column of protein names, followed by a column of protein length, followed by columns of spectral counts (these are from the NUMSPECSTOT columns in abacus output). For the spectral count columns, I am comparing replicates of two treatments: these can be biological and/or technical replicates (note that qspec only accepts whole numbers so you cannot average spec counts for the input). There can be many columns of spec count input but make sure your comparisons make sense for your experimental design. It will compare all the 0 columns as a group will all the 1 columns as a group.

Sorry, internet is slow and I cannot attach files. I will email them to @kubu4 to upload.

**Comment by kubu4** [comment]
Ah, here's the issue I'm having retrieving that file: http://www.theverge.com/2017/2/28/14765042/amazon-s3-outage-causing-trouble

**Comment by kubu4** [comment]
The two files @emmats emailed me are here (and viewable on GitHub):

- [ABACUS_output_trim_tran.txt
](https://github.com/sr320/LabDocs/blob/master/templates/ABACUS_output_trim_tran.txt)

- [https://github.com/sr320/LabDocs/blob/master/templates/copepodqspec.txt](copepodqspec.txt)

Both files were truncated to only 9 rows for simplicity of viewing. The ABACUS output file was also renamed to reflect the trimming and the fact that I translated it from CSV to TSV (using bash tr command).

@emmats - There are significant differences between these files. Can you please walk us through how you got from the ABACUS output file (which doesn't have the NUMSPESTOT column as mentioned in your previous post, as well as many more columns than the Qspec file) to the Qspec file?

**Comment by emmats** [comment]
Sorry, that was an abacus file that I had edited. Here is the correct one.


[ABACUS_output.xlsx](https://github.com/sr320/LabDocs/files/809378/ABACUS_output.xlsx)
It is very simple to get from the abacus file to the qspec input file. The abacus file has protid and protlen columns, both of which you need for qspec. It has many other columns, but the ones you are interested in have the format sample name_NUMSPECSTOT. You can just select your columns of interest for a qspec input file in any program you use for that and then rename the column headers appropriately for qspec (outlined clearly on their website). Make sure the file is saved as windows formatted text and that there are no spaces in the file name.

**Comment by kubu4** [comment]
@emmats - Thanks, but that is not an ABACUS output file (I'm fairly sure ABACUS doens't produce .XLSX files).

When you have the chance, could you please provide us with an ABACUS output file and a corresponding Qspec file, and walk us through how you modified the first file to achieve the second file?

**Comment by kubu4** [comment]
@emmats - Sorry, I was a being a bit pedantic about that most recent file format; just trying to emphasize that using Excel to save intermediate files in a pipeline is bad form. 

To get back on track, can you please describe the steps you took to modify the ABACUS output file to get ready for submission to Qspec.

I think the following information would be helfpful:

- Can you please describe your experimental design (i.e. how you decided which NUMSPECSTOT columns to keep) so that we can get an idea of how you assigned 0 and 1 to particular samples?

- Can you please detail the steps you took to whittle down from 400 columns in the ABACUS output file to 15 columns in the Qspec file (e.g. provide us with R code used, or tell us how you manipulated the file in Excel [ugh])?

**Comment by emmats** [comment]
github wouldn't let me upload a .tsv. 

Yes, I usually do this in excel. I delete the columns I don't need and save as. Oh, horror! But the columns all have names, so I can easily see if I grabbed the wrong ones. I choose the columns that are relevant to my experimental question. I include all technical replicates. In the copepod example that I uploaded, there were only two time points so I compared everything from 2 am to everything from 8 pm and assigned 0 to one of those time point columns and 1 to another. It is really quite simple. I think you may be overthinking this.

The abacus editing can also happen easily in R. You can use subset to select the columns you want. Then you would want to sum all the columns and make sure you get rid of the rows that sum to 0 (these are uninformative as the proteins were not detected in the samples you are comparing). Then make sure the column names are correct and export. I am not sure how to export in the correct format from R, which is why it is easiest to do in excel. Since I (and most of you) use Macs, it really needs to be saved as a windows-formatted txt file, which is an option in excel.

You can apply whatever pipeline you want. This shouldn't be this difficult.

**Comment by sr320** [comment]
@seanb80 were you able to re-run to get the missing 20A file?

**Comment by seanb80** [comment]
I was, but I just looked at the output file and it again did not appear... trying to figure out why.

**Comment by seanb80** [comment]
[ABACUS_output.tsv.zip](https://github.com/sr320/LabDocs/files/812203/ABACUS_output.tsv.zip)

This has the 20A file also, not sure why it didn't include it last run.
