### ISSUE TITLE
screen sharing w/ genefish

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#495]
I want to use screen sharing to get into genefish and use jupyter notebooks since my computer keeps crashing. However, anytime I try and to screen share I get this error message:

![screen shot 2017-02-22 at 9 16 09 am](https://cloud.githubusercontent.com/assets/22335838/23223311/913220b0-f8df-11e6-8a52-c1469ecae4bc.png)

I looked at the settings on genefish and it seems like everything should be set up correctly. Any suggestions?

**Comment by kubu4** [comment]
Genefish doesn't have an internet connection. May I restart genefish to see if that resolves the issue?

**Comment by yaaminiv** [comment]
works for me!

**Comment by kubu4** [comment]
Restarting. Will report back shortly.

**Comment by sr320** [comment]
Would not ssh tunnel with tmux be recommended for remote Jupyter?

**Comment by yaaminiv** [comment]
I'm just trying not to do anything through my own computer because even opening terminal is wreaking havoc. I think it should be able to handle screen sharing, which would allow me to connect to emu for all of the proteomics analyses through genefish.

**Comment by kubu4** [comment]
This should be resolved. 

The issue was due to a change in IP address (assigned by UW IT). 

See [Roberts Lab Computers Google Sheet](https://docs.google.com/spreadsheets/d/1mtIITcjqZVEQtynYZFdOdx51uXTiXP7Jvvzv_SnWCDY/edit#gid=0) for new address.

Additional info, just for posterity. They converted the old manually assigned IP address (i.e. static - shouldn't change) to a new IP address (which is currently assigned via DHCP - meaning the IP address may be changed dynamically as UW IT sees fit). This change in IP addresses is part of a security upgrade the UW is implementing. The new IP address is in a group of IP addresses that are not accessible outside of the UW network. The new IP address should be more secure.

However, I think Remote Desktop still works from outside of the university...

**Comment by kubu4** [comment]
@yaaminiv - I think you should resolve your computer's issue(s) before bothering with any remote access. If you can't run Terminal, then I wouldn't have much confidence in Screen Sharing being more stable...

Until then, I'd highly recommend physically sitting at Emu.
