### ISSUE TITLE
Any way to search Jekyll GitHub notebooks?

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#503]
For example, I'm trying to search @hputnam 's notebook to find which samples she gave to @jldimond for sequencing.

For the record, @jldimond already gave me the list, but I wanted to link to Hollie's notebook from my notebook where she identifies which samples she gave to @jldimond. However, I can't seem to figure out any easy way to do this.

Any suggestions? (Do you have to go to the actual repo with the Jekyll files and search there?)

Separate issue, using @hputnam doesn't autocomplete any more when typing??!! Anyone know why?

**Comment by sr320** [comment]
The only way I know is to search to repository ...  If this ends up to the only way, all of us could put links for such a search on our notebooks page. Also maybe a custom Google search link...

I think it will not autocomplete on this repo because she refuses to accept our invitation for collaboration :)

![img_0134](https://cloud.githubusercontent.com/assets/4442039/23388931/ce55afc8-fd19-11e6-8d47-af36e1035fd0.PNG)

**Comment by hputnam** [comment]
:running:  :computer:

**Comment by hputnam** [comment]
Hahaha no wonder I could never figure out how to add labels!!!

**Comment by hputnam** [comment]
@kubu4 at the bottom of this post https://hputnam.github.io/Putnam_Lab_Notebook/Geoduck_Larval_DNA_Extractions/

**Comment by kubu4** [comment]
Thanks!

**Comment by seanb80** [comment]
While I told Sam the answer to this, I'll answer the question here for posterity.

There is not a way to search static page sites such as one created with Jekyll, due to the fact there is no single database to search. 

There are some workarounds that involve creating a temporary JSON database which is then searched. I'm working on implementing one on my page, but GitHub pages is being difficult about executing javascript.
