### ISSUE TITLE
Install software on genefish (mac mini in FTR 230)

### ISSUE THREAD

**Issue by kubu4** [sr320/LabDocs#514]
Please install standard bioinformatics software on macOS partition.

Please install Windows-based proteomics software (e.g. MSconvert, Skyline, etc) on Windows 7 partition.

To boot into Windows, restart the computer and then hold the ```option``` key. Select the Bootcamp Windows startup disk when the choice presents itself.

**Comment by seanb80** [comment]
Will do. Do you want the windows 7 partition upgraded to windows 10 for bash/powershell access?

**Comment by sr320** [comment]
I say we buy an updated Windows machine.

On Tue, Mar 7, 2017 at 7:38 AM seanb80 <notifications@github.com> wrote:

Will do. Do you want the windows 7 partition upgraded to windows 10 for
bash/powershell access?

> On Mar 7, 2017, at 6:24 AM, kubu4 <notifications@github.com> wrote:
>
> Assigned #514 to @seanb80.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sr320/LabDocs/issues/514#issuecomment-284757242>, or mute
the thread

**Comment by kubu4** [comment]
Has the standard bioinformatics stuff been installed on the macOS partition?
