### ISSUE TITLE
can't run command line MSConvert on Windows in lab

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#518]
I'm trying to convert 1 of my .raw files to an .mzML file on the Windows machine. I had to install the ProteoWizard tools (includes MSConvert) and Git Bash so I could use the code from the Evernote entry.

![code](https://camo.githubusercontent.com/ed609b45f8aeaf4ff6a375ac7732c71f7d2a8af5/68747470733a2f2f636c6f75642e67697468756275736572636f6e74656e742e636f6d2f6173736574732f32323333353833382f32333638383731302f66393738306466632d303336612d313165372d396131382d3166353631306266363533302e706e67)

Everything I've done so far is in my lab notebook: https://github.com/RobertsLab/project-oyster-oa/blob/master/notebooks/2017-03-07-Reconvert-mzML-Files.ipynb

Now, I'm unable to actually run any command. This is what I've tried so far:

![msconvert](https://cloud.githubusercontent.com/assets/22335838/23690363/e219a85e-0375-11e7-91b3-02b20d16abd6.png)

For clarity, here are the paths to the relevant programs/files:

**msconvert.exe**: C:\Program Files\ProteoWizards\ProteoWizard 3.0.10577\msconvert.exe

**config file**: /c/Users/srlab/Documents/2017-03-07-MSConvert/msconvert-SIMMS1.config

**file to convert**: /c/Users/srlab/Documents/2017-03-07-MSConvert/2017_January_23_envtstress_oyster1.raw

What should I do now?

**Comment by kubu4** [comment]
You need to use the Windows command line, not GitBash.

Do the following:

1. Open the Start Menu (the circular Windows icon in the lower left)

2. Search for ```cmd.exe```

3. Select the result (should be something like "Command Prompt")

4. Now, run MSconvert following the example in the Evernote tutorial. Specify the path to MSconvert in the following fashion (you'll need the double quotes): ```"c:\Program Files\ProteoWizard\ProteoWizard 3.0.10577\msconvert.exe"```

Other things:

- To see a list of files, you need to use ```dir``` instead of ```ls```

- You may want to change directory to a single folder that contains your .raw file and operate from there

- The link you provided isn't your notebook. It is A notebook. Your notebook is here: [https://yaaminiv.github.io/](https://yaaminiv.github.io/) . Please be sure to make an entry in your notebook (since this is where people will be looking to follow along with what you've been up to). As @sr320 mentioned previously, you can just put a link to your Jupyter notebook in your actual notebook post; no need to spend more time than that.

**Comment by yaaminiv** [comment]
I was about to post a screenshot showing my revised code worked, but then the computer crashed. The screen I saw said something along the lines of "there's been a problem detected so the computer is restarting."

More to follow...

**Comment by yaaminiv** [comment]
I was able to successfully convert the files using the following code:

```
cd C:\Users\srlab\Documents\2017-03-07-MSConvert

"c:\Program Files\ProteoWizard\ProteoWizard 3.0.10577\msconvert.exe" -c C:\Users/srlab/Documents/2017-03-07-MSConvert/msconvert-SIMMS1.config C:\Users/srlab/Documents/2017-03-07-MSConvert/2017_January_23_envtstress_oyster1.raw
```

And thanks for clearing up the distinction between my personal notebook/a jupyter notebook I'm using! I had a post earlier that I'm working on updating, so here it is:  https://yaaminiv.github.io/PECAN-Update-2/
