### ISSUE TITLE
Notebook Backup

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#52]
Lets pretend the internet broke. 

Where is your local backup of your lab notebook?

How did you create this?

**Comment by kubu4** [comment]
Currently, not backed up.

Will start running weekly exports. Will export using the ONS Wordpress export function. Exports entire notebook as an XML file.

Will save weekly exports in Eagle/archive/notebooks.

**Comment by sr320** [comment]
Would be great to have automated

**Comment by jheare** [comment]
Currently the olywiki is backed up on Eagle. The Blogger account has not been backed up to an offline source recently, the last offline copy from November is on Eagle as well.. I do however keep digital copies in my Google Drive though IFTTT seems to have issues with it randomly.

**Comment by jheare** [comment]
[Here is the link](https://docs.google.com/document/d/1lozqv9oSbx4RD5Ua0kNIGIGjQ27BweSCSBAnxWIkMYE/edit?usp=sharing) to the plain text document that IFTTT produces on Gdrive for me when I update my blogger notebook. It should work the same for wordpress accounts as well.

**Comment by sr320** [comment]
Formatting is quite bad with that recipe and lack of images seems to be issue.

So far ifttt to gmail and evernote seem to be best to maintain formatting.


<img src="http://eagle.fish.washington.edu/cnidarian/skitch/Evernote_Premium_1A9FE4A4.png" alt="Evernote_Premium_1A9FE4A4.png"/>

**Comment by sr320** [comment]
Steven needs to ping ons again?

**Comment by sr320** [comment]
answer via ons

http://onsnetwork.org/members/steven-roberts/activity/1182/

**Comment by jheare** [comment]
I just backed up the template and XML file for the research blogger blog. Its stored on Eagle. This should hopefully keep the pics and everything intact unlike the IFTTT function.

**Comment by sr320** [comment]
Getting closer with SiteSucker and wget- but nothing automated yet

**Comment by kubu4** [comment]
I have a script that I put together this weekend to automatically pull HTML versions of everyone's (non-Wiki) notebooks. I plan on putting the script on Eagle and setting up a ```cron``` job to run the script regularly.

Additionally, the script uses ```git``` to apply version control to the notebooks.

However, I'd like to review how "thorough" the backups need to be (e.g. do FASTQ files need to be accessible?), as well as review best practices for notebook entries. The reason for the latter is that things like NBviewer won't display in offline notebooks w/o an internet connection, so notebook entries with NBviewer embedded in the notebook should probably also have a directly link to the Jupyter notebook file so that the file gets downloaded to the offline copy.

Along these lines, I need to test out what happens with Google Docs. Not sure they are successfully downloaded. If they are not (and I'm unable to figure out a way to do so), what should the notebook guidelines be for notebooks and using Google Docs?

**Comment by kubu4** [comment]
Got the Google Docs to download without issue, so that's cool. Of course, I think the docs have to be publicly shared in order to grab them.
