### ISSUE TITLE
Explore oyster larvae proteomics data

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#530]
Have a look at the project description
https://github.com/RobertsLab/project-pacific.oyster-larvae/wiki/2016-Oyster-Seed-experiment-23C-vs.-29C

Then take the following data into Excel and see if you can ID proteins (each row) that are expressed at a high level and vary across samples. 
https://github.com/sr320/nb-2017/blob/master/C_gigas/data/ABACUS_output021417NSAF.tsv

Just post any Questions here.
Thanks

**Comment by kaitlynrm** [comment]
I'm not sure if I'm missing the excel spreadsheet with proteins, but I noticed the same link is posted twice and I can't seem to find the excel document to work on in the project description.

**Comment by sr320** [comment]
Sorry about that - I edited the post above-
file is https://github.com/sr320/nb-2017/blob/master/C_gigas/data/ABACUS_output021417NSAF.tsv

**Comment by kaitlynrm** [comment]
[oyster data (ABACUS_output021417NSAF) EDIT.xlsx](https://github.com/sr320/LabDocs/files/859734/oyster.data.ABACUS_output021417NSAF.EDIT.xlsx)

I have calculated the average, range (as a max-min value), median, and range (as a max-min value) of the data and conditionally formatted it to represent values by color and data bars. This gives me a pretty good idea of protein expression levels and variance. Now I'm not sure which proteins to denote as highly expressed. There are very few proteins expressed above 100. I can either ID just these proteins or select the top 10 (or whatever) percent. The range is a bit more tricky for me as there seems to be quite a few outliers in the data set and I'm not sure if you'd like me to include those as variable or mark those separately.

**Comment by Ellior2** [comment]
Wow, thank you! I am still working on the NMDS to compare our duplicate runs on the MS. However, I am just briefly looking over the a few of the protein expression levels and am pretty concerned with our technical replicates (denoted by the "sample #" and then the "sample#A"). Looks like the NSAF values were used. 

For example... Sample 43 and 43A had expression levels of protein CHOYP_TBB4B.7.7|m.63980 (Line 8) of 0 and 70 respectively. Another one that stood out is Sample 48 and 48A which had expression levels of protein CHOYP_MYSP.4.9|m.2302 (Line 21) of 219 and 0 respectively. I am sure there are many others, this is just what caught my eye in the 10 minutes I looked at it. Huge red flags. @emmats have you seen this with your data?

**Comment by kaitlynrm** [comment]
I noticed that in the data as well... especially when an outlier was evident from the median value. I added in values for the technical replicates to compare to original samples and flagged any that were greater than 10 different if you want to take a look at any that may have significantly affected the total data calculations. 

[oyster data (ABACUS_output021417NSAF) EDIT.xlsx](https://github.com/sr320/LabDocs/files/859900/oyster.data.ABACUS_output021417NSAF.EDIT.xlsx)

**Comment by kaitlynrm** [comment]
I noticed that in the data as well... especially when an outlier was evident from the median value. I added in values for the technical replicates to compare to original samples and flagged any that were greater than 10 different if you want to take a look at any that may have significantly affected the total data calculations.

[oyster.data.ABACUS_output021417NSAF.EDIT.witherror.xlsx](https://github.com/sr320/LabDocs/files/859906/oyster.data.ABACUS_output021417NSAF.EDIT.witherror.xlsx)

**Comment by emmats** [comment]
@Ellior2 that seems very odd. I do not usually see such large discrepancies between technical replicates. For some of those proteins that are high expression in one replicate and 0 in another, go back to your original data file (probably your protein prophet file) and make sure that the files were merged correctly.

**Comment by Ellior2** [comment]
@seanb80 I'm unsure where those intermediate files live from the last run you did or the command line output that might lead us to believe there was an error. Can you please help me out with this? Thank you!

**Comment by sr320** [comment]
Please create a new issue for file request.

**Comment by Ellior2** [comment]
So I just started honing in on sample 35 and 35A which represents Silo 2 oysters at 23C at Day 11 (phenotype: high mortality) and 43 and 43A which represents the same group of oysters at Day 13. I wanted to look into these because they were outliers in this NMDS plot https://github.com/sr320/LabDocs/issues/510

After looking those over, it just seems like those samples had less protein expression than the rest. I summed up each column (added ADJNSAF values for each protein within each sample) and it is clear that those samples had about half of the total protein expression compared to the rest which probably explains why they were so far away from the rest on the NMDS plot.

Being new to the field of proteomics, I guess I assumed to see greater protein expression for certain proteins associated with stress. It appears these oysters from Silo 2 that were under stress during these final days of the experiment expressed less of the proteins that were highly expressed in our other samples. So for some unidentified reason, these oysters are not producing the proteins that appear to be required for successful growth and development...

**Comment by emmats** [comment]
I think you need to rule out that it is not just less protein loaded into the mass spec. We can look at the total ion current to estimate this. If you give me the file numbers, I can give you the TIC values. It would also be good to get TIC for some "normal" protein level samples.
Have you considered metabolic suppression in the stressed oysters?
You should also try to figure out if it is less overall protein abundance (lower spectral counts) or fewer proteins were detected. Can you figure out how many proteins were detected in these samples compared to others?

**Comment by kubu4** [comment]
>I think you need to rule out that it is not just less protein loaded into the mass spec. We can look at the total ion current to estimate this. If you give me the file numbers, I can give you the TIC values.

This seems like it should be the very first step before any analysis is done, right?

Also, can you please provide deets/protocol on how this is performed?

**Comment by emmats** [comment]
The only way I know how to look at TIC is by opening a raw file. The number is on the raw file (see attached, TIC is boxed in red). However, you need the thermo xcalibur software to view these files. Another way to see if you have any raw files that look different from the others is to compare all your files in the free software raw meat. I believe @Ellior2 did this already. With raw meat you can see the number of MS1 and MS2 scans and other pieces of relevant information.
![screen shot 2017-03-23 at 10 04 49 am](https://cloud.githubusercontent.com/assets/4564812/24260301/b91fb6e0-0fb0-11e7-993a-24b965088b23.png)

**Comment by Ellior2** [comment]
I did do this while we were running the mass spec and I do recall a couple samples being on the lower side. I don't have my notes with me right now but I wouldn't be surprised if those were the ones. I remember Emma and I had talked about it at the time and thought we'd be fine.

It seems like these samples had less proteins detected AND less overall protein abundance. Most of the samples had anywhere from 3500-4500 total proteins detected and samples 35/35A had about 2300 and 43/43A had about 2900. I was speaking with Brent last night and he suggested perhaps protein degradation is occurring as these oysters are dying. Although we standardize the amount of protein used in the analyses, perhaps the proteins are degraded and unable to be detected. Should we be looking at relative abundances of each protein within each sample?

**Comment by emmats** [comment]
Please still give me some file numbers so we can directly compare TICs for the reduced and normal protein abundance samples.

It can't hurt to compare relative abundances of proteins. You could just do a simple scatter plot of protein abundances from two samples (a reduced and normal).

**Comment by Ellior2** [comment]
Do you have all of my files? If so, the samples with low protein abundances are 35, 35A, 43, and 43A.

**Comment by emmats** [comment]
Here are the TICs (I chose 32 and 32A and 12 and 12A as comparison points):
32 = 1.95E10
32A = 1.91E10
35 = 7.21E9
35A = 6.76E9
43 = 1.2E10
43A = 1.14E10
12 = 1.85E10
12A = 1.83E10

It looks like TIC is probably lower in those two samples. This could be technical (less protein was loaded, in which case you should not include these in analysis) or biological (for reasons similar to what Brent discussed with you).

I compared number of MS2 scans between files for 32, 35, and 43. For 32, the number of MS2 scans is ~99K (this is about the same as the one I have in my lab notebook, sample 28, with MS2 scans = 98K). The 35 samples have ~87K and the 43 have ~90K. This evidence points towards differences due to technique rather than biology. Probably, there was less protein loaded for 35 and 43 and so the lower abundance proteins that are captured by the mass spec for samples 32 and 28 are at too low of a level to be detected.

Another way to follow up on biological vs. technical is to compare spectral counts for proteins that you would expect to be stable no matter what. I'm not sure what these would be, you'll have to do some research. People frequently use actin and myosin, but those can change in abundance in certain scenarios as well. You should look for trypsin and see if trypsin abundance is the same throughout the experiment since you added the same amount to each sample and should have loaded the same amount with each.

**Comment by Ellior2** [comment]
![image](https://cloud.githubusercontent.com/assets/20071030/24269432/6fd7bfbe-0fce-11e7-8afc-3e5717a95d1a.png)

I found TRYP_PIG when I just searched "TRY" in excel. If this is it, the expression level is in the same range of the other samples which is 4-7.

The MS2 scans also seem lower for samples 35 and 43(87-90K vs. normal abundance 98-99K). Why again does this lead you to believe it is technique, not biology? If MS2 scans were normal, but MS1 scans were not, you would think it could be biology?

I guess I just have a hard believing that out of the 22 samples I had, the two that for whatever reason may not have had enough protein loaded into are from the silo that experienced high mortality during that time frame the samples were collected.

**Comment by emmats** [comment]
I agree, but I also haven't seen any evidence that points definitively to biology. Except that the number of trypsin peptides detected is the same.

Regarding the MS2 scans, the mass spec detects the peptide in the MS1 scan and then fragments it and does MS2 on the fragments until it has sampled however many it can before moving on to the next one. So if there are a lot of detectable fragments, you will have more MS2 scans; if there aren't many fragments (due to low protein abundance perhaps) then it will not "fill up" and will move more quickly through the peptides.
