### ISSUE TITLE
Provide Inventory Map on -80 Freezer door

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#564]
Maybe this is already done - 
But if not, design paperwork that would indicate what is in each shelf of the -80s (both)
such that someone could reference standing in front of it.

**Comment by grace-ac** [comment]
This is the google spreadsheet with all the information. I just rearranged the trays in the -80 so that they're in order and rearranged the sheet accordingly. 

Too much info? It's about 6 pages.... 
[-80 Inventory Map (Condensed) - Sheet1-2.pdf](https://github.com/sr320/LabDocs/files/911180/-80.Inventory.Map.Condensed.-.Sheet1-2.pdf)

**Comment by kubu4** [comment]
@grace-ac - I was thinking something more visual - like a pictographic representation of the physical freezer and its contents.

**Comment by grace-ac** [comment]
![img_3121](https://cloud.githubusercontent.com/assets/14934314/24882627/96757d1a-1df6-11e7-9dd8-225f8f7ed956.jpg)

**Comment by grace-ac** [comment]
4 shelves. each shelf has sheets posted on outside of freezer with racks and their contents. literally just the google spreadsheet separated by shelf.
