### ISSUE TITLE
OWL blocked on Woodpecker IP

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#578]
![image](https://cloud.githubusercontent.com/assets/22335838/25072544/f950fade-2285-11e7-83e9-1e396daacd2e.png)

I forgot OWL made me change my password and then this happened.....whoops. What can I do to fix this?

**Comment by sr320** [comment]
What is Woodpecker IP? can just to browser and type what is my ip...

**Comment by yaaminiv** [comment]
Oh I just left SAFS but I'll probably be back there in the evening to check on file conversions and can look it up then

**Comment by sr320** [comment]
Assuming it is 183........... and it happen at 9:20AM, Woodpecker should now be unblocked.

**Comment by laurahspencer** [comment]
It's 205.175.118.180

**Comment by kubu4** [comment]
It should be the 172 address.

I've added that IP address (the 172 addres) to the Roberts Lab Computers spreadsheet.

I've also added that IP address to the "Allow" list on Owl, so failed logins to Owl from Woodpecker shouldn't be an issue in the future

**Comment by laurahspencer** [comment]
FYI the address I provided was found via typing "what's my IP" in the
browser on Woodpecker

**Comment by kubu4** [comment]
Interesting. That address wasn't listed as blocked by the system, nor is it part of the UW IP subnets (UW IP addresses start with 172 or 128).

**Comment by kubu4** [comment]
One last thought on this. The 172 address is a UW-only subnet. Meaning, that IP address is not accessible outside of the UW network. I'm guessing that this IP address (as opposed to what Laura posted for the IP address) is what was seen by Owl (and subsequently banned) because Owl was being accessed from within UW's network, as opposed to outside of the UW network. If it was the latter, I think the IP address Laura posted would've been banned instead.
