### ISSUE TITLE
Image OA oyster larvae

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#612]
Image larvae in the 50 ml tubes so that one could accurately measure 100 individuals.

Please do one image (post) and lets confirm it will work.

**Comment by grace-ac** [comment]
Here's the best attempt I've done so far: 
![oalarvae](https://user-images.githubusercontent.com/14934314/27885911-9cdb1f1c-618e-11e7-85c4-9ebb546823b2.JPG)

Unsure of how well this will end up working. As is- with 89 larvae - they are too small and blurry to accurately measure. Not sure how feasible it is to have one image with 100 individuals.

**Comment by grace-ac** [comment]
I guess it's actually not so bad - when zoomed in to try to measure, you can sort of discern the borders of the larvae and could estimate their sizes.

**Comment by djgillon** [comment]
Hi Grace - thanks so much for helping with this. A couple suggestions:
- Try adjusting the backlighting to improve the contrast in the dish. We'll be doing the measurements with software that lets us zoom in really closely, so having clear photos at low magnification is fine. 
- For each sample, need a single photo that includes both the hemacytometer grid and tube label before any larval photos taken. ****Make sure that you don't adjust the zoom in any subsequent photos of that sample once you photograph the grid!** You can adjust the zoom as needed for the next tube, etc. 
- Label the squares in the grid, then take several photos of the sample to get adequate numbers.


Happy to swing by the lab if you'd like. - Dan

**Comment by grace-ac** [comment]
@djgillon 
Okay, so using a hemacytometer probably won't work, because the larvae are quite large: 
![hemacytometer](https://user-images.githubusercontent.com/14934314/28338899-31d791ce-6bbf-11e7-9031-a0fa05a0826e.JPG)

I think I originally mis-understood: I thought that the goal was to get 100 larvae in one image. 

Does something like this work better? I can get much clearer images. And there's a grid in each image. The grid is 1mm. I will not adjust magnification within a tube group. There will be more images per tube group than there would be using the other method, but the larvae are much clearer. If this seems like a good method, I can continue taking images in this manner. 
![img_3916](https://user-images.githubusercontent.com/14934314/28339915-b333a6a6-6bc2-11e7-9396-e6e8472b2833.JPG)
![img_1214](https://user-images.githubusercontent.com/14934314/28339921-b87fea84-6bc2-11e7-8c05-b99a69611c57.JPG)

**Comment by djgillon** [comment]
Hi Grace, 
You don’t need to take a picture of the larvae on the hemacytometer. I meant take a photo of the hemacytometer first, then start taking photos of larvae in the gridded petri dish without adjusting the zoom. I am on campus and can show you.

Dan



Daniel Gillon
djgillon@gmail.com
(301)641-8355

**Comment by grace-ac** [comment]
Oh, ok! I understand now. I'll take some images and post them here.

**Comment by kubu4** [comment]
This issue was moved to RobertsLab/resources#8
