### ISSUE TITLE
ID Oly Gonad Samples for RNA-Seq

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#631]

**Comment by sr320** [comment]
Need 4-9 low pH samples and 4-9 control samples...

**Comment by laurahspencer** [comment]
Here are my thoughts: 

Ideally I'd like to run samples from both North Sound and South Sound, and a male, female, and hermaphrodite from each of the low pH and ambient pH groups. I assume these won't be pooled?  If we do 3 samples from each site/treatment, one per sex (no rep), they are as follows: 

SN low pH
 1. male
 2. female 
 3. hermaphrodite

SN ambient pH
 4. male
 5. female 
 6. hermaphrodite

NF low pH
 7. male
 8. female 
 9. hermaphrodite

NF ambient pH
 10. male
 11. female 
 12. hermaphrodite

What do you guys think? We can narrow down the site/sex by either doing only South Sound, or not using hermaphroditic individuals. 
I'll use Katie's images of the histology slides to ID sex and generous presence of gonad.

**Comment by sr320** [comment]
Are their gonad samples in -80 that correspond to slides?
IOW do we extract from tubes or histo cassettes?

**Comment by laurahspencer** [comment]
I only have go ad samples fixed in the histology cassettes. In the freezer
at Manchester I have ctenidia, mantle, and adductor, and I also have excess
tissue in ethanol.

**Comment by sr320** [comment]
Images are at 
https://drive.google.com/drive/u/1/folders/0B6vcfZRVqdYHUVQ0ZmZ3VTlpYkU

for sex determination of individuals

**Comment by laurahspencer** [comment]
Any input on the # of each sex/location? Should we loop in Katherine?  

If we move forward with the below, here are sample ID's, and the [histology key](https://laurahspencer.github.io/LabNotebook/Prepping-Histology-Samples/) for reference (We should work with Katie to make sure we sample the correct tissue in each cassette). I've selected all from the "overwintered" temp of 10degC, since their gonads appeared more developed than the 6degC. 

SN low pH
 1. male - SN-10-20
 2. female - SN-10-16
 3. hermaphrodite - SN-10-17

SN ambient pH
 4. male - SN-10-25
 5. female - TBD; still need images from SN-10-27 through 33 
 6. hermaphrodite - SN-10-26

NF low pH
 7. male - NF-10-24
 8. female - NF-10-23
 9. hermaphrodite - NF-10 22

NF ambient pH - (missing image for NF-10-25)
 10. male - NF-10-28 (not 100% male, a few oocytes)
 11. female - NF-10-30
 12. hermaphrodite - NF-10-26

**Comment by sr320** [comment]
It will be two pools, Ambient and low pH.
This is designed as reference that could later be used for tag-seq for
individual gene expression.

**Comment by sr320** [comment]
@laurahspencer 
More images were taken today
can you see if you can decide on

5. female - TBD; still need images from SN-10-27 through 33

**Comment by laurahspencer** [comment]
Updated my previous comment. 
@kubu4, you'll probably want to work with Katie to make sure that you're extracting from the same sample as the one she imaged. The histology folks did not keep the samples in the same formation. Katie used my [images of the prepared cassettes](https://github.com/laurahspencer/LabNotebook/blob/master/_posts/2017-04-20-Prepping-Histology-Samples.md) and my [histology "map"](https://github.com/laurahspencer/O.lurida_Stress/blob/master/Data/2017-April-HistoKey.pdf) to ID each sample.
