### ISSUE TITLE
Stage Olys based on histology 

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#649]
@katiedavidson5 (note please accept repo invite so you can be assigned) 
Go ahead and try to stage all the pics you have taken

@grace-ac and @laurahspencer can you please provide some references for this. 
It would make sense to follow previous published reports.

I suggest doing this somewhere on the web so we can all see pics and prospective reproductive stages - maybe Google Docs or Github (markdown).

**Comment by grace-ac** [comment]
I sent a link to a shared folder of mine that has two papers on staging i
found to Katie a while back. Will make more easily accessble for all when i
get to my laptop!

**Comment by laurahspencer** [comment]
I believe the two papers Grace is references are the [Moore 2016](https://github.com/sr320/LabDocs/files/1123794/Sexual.development.and.symbionts.of.native.Olympia.oysters.Ostrea.lurida.naturally.settled.on.cu.1.pdf), and the [Oates 2013](https://scholarsbank.uoregon.edu/xmlui/bitstream/handle/1794/13329/Oates_oregon_0171N_10767.pdf;sequence=1).  I like and would recommend using Oates' stages, sex/maturity as they capture both comprehensively, and he provides nice color images as reference: 

![image](https://user-images.githubusercontent.com/17264765/27853506-c6c4e9ce-6117-11e7-825c-45af9ebb4ee2.png)
![image](https://user-images.githubusercontent.com/17264765/27853543-e9e7090a-6117-11e7-8baf-c8b4510b1386.png)
![image](https://user-images.githubusercontent.com/17264765/27853646-5dd00bfa-6118-11e7-823d-ab5e17af9d77.png)
![image](https://user-images.githubusercontent.com/17264765/27853654-65b8898c-6118-11e7-81ea-6fcd3c9a29f3.png)

The Moore paper can provide additional images/reference, but they specifically looked at oysters <1yr old, so they are developing their first gonad tissue and thus isn't as applicable.

**Comment by katiedavidson5** [comment]
@sr320 I did a preliminary staging of all the pictures according to the Oates paper, as suggested by Laura, in the details section of each of the "low" magnification images on the google drive. They are coded sex, stage. 
Key for Sex:
M=Male, F=Female, HBS=Hermaphrodite (equal), HPM=Hermaphrodite (predominately male), HPF=Hermaphrodite (predominately female)
Key for Stage:
1= Early, 2=Advanced, 3=Ripe

I still have some questions about the stages, but since it is all on the google do it can be easily edited! I also have a hard copy of all the stages, so if we have to group them by stage at some point we won't have to go back and click through every picture.

**Comment by laurahspencer** [comment]
Very cool; I'd love to check out the hard copy data when you come in. Did you stage both pre- and post- OA treatment slides, or only the post-OA treatment (the ones you imaged)?

**Comment by sr320** [comment]
Completed
https://genefish.wordpress.com/2017/07/11/71017/
