### ISSUE TITLE
Obtaining GOSlim information with UniProt IDs

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#655]
What are the best / different ways to do this?

**Comment by laurahspencer** [comment]
I too would like to know how to do this

**Comment by Ellior2** [comment]
The more I think about it as I work through it, the more logical it seems to go directly to GO slim. When I unfold the GO terms for one protein and merge those GO terms with GO slim categories, I end up "doubling up" on the level of expression, if that make sense. Here I am working on 2016 data looking at Sample 1. As you can see many of the GO terms from one protein end up matching to the same GO slim category (makes sense). However since I want to use the NSAF values as a level of expression, I don't know if it really makes sense to sum these values like I did in the pivot table. My goal is to make a pie chart of the GO slim categories with relative expression to show resource allocation.

![image](https://user-images.githubusercontent.com/20071030/28101665-d9c789e8-667e-11e7-910b-ce9c9d080887.png)

**Comment by sr320** [comment]
This should get you from Blast output to GO slim without leaving Jupyter.

https://github.com/sr320/nb-2017/blob/master/misc/10-blast-2-slim.ipynb

![drop](https://static1.squarespace.com/static/551e1babe4b0aa77af01e45f/t/572bbda31d07c0c02000bb09/1462484399168/)

**Comment by kubu4** [comment]
Baller!
