### ISSUE TITLE
More gigas larvae materials

### ISSUE THREAD

**Issue by yaaminiv** [sr320/LabDocs#671]
Airline tubing (replacing Joth's) (Quantity: 1) http://pentairaes.com/silicone-tubing-3-16.html?gclid=Cj0KCQjwqvvLBRDIARIsAMYuvBEmyFGcyZou3ZVJGQzI7f-3fiaUkITB6Y9bcoMtuVz33vtRayuRxDkaAjAjEALw_wcB

Additional heaters (Quantity: 2) https://www.amazon.com/gp/product/B003GVT0V0/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1

@sr320 Is it also possible to get more HOBO data loggers? It would be nice to have one in each larval bucket meaning I would need 10 more.

**Comment by laurahspencer** [comment]
FYI:

I found 2 HOBOs and keep forgetting to bring them to Manchester; I will do so on Saturday, but you should grab spare batteries in case they need them (should be in the lab where HOBOs are kept)

You can have the heater that's in my outside tank- I don't need it anymore due to high water/air temps. I unplugged it today- feel free to take it tomorrow.

I too used a ton of PSRF's airline tubing; it would be nice to replenish the supply - perhaps order 1 more roll?

**Comment by Ellior2** [comment]
I have 8 hobo loggers for you Yaamini, just a matter of getting them to you...

**Comment by yaaminiv** [comment]
In that case, I don't need to order any more HOBOs and I may hold off on the immersion heater. Thanks @Ellior2 and @laurahspencer!

Revised order:

Airline tubing (replacing Joth's and PSRF's) (Quantity: 2) http://pentairaes.com/silicone-tubing-3-16.html?gclid=Cj0KCQjwqvvLBRDIARIsAMYuvBEmyFGcyZou3ZVJGQzI7f-3fiaUkITB6Y9bcoMtuVz33vtRayuRxDkaAjAjEALw_wcB

**Comment by kubu4** [comment]
@sr320: 61-0221?

**Comment by sr320** [comment]
yes please
